// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.ava.ChatConfig in ava.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.ava

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Chat configuration
 */
public class ChatConfig(
  /**
   * LLM model to use
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val model: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val temperature: Float = 0f,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "maxTokens",
    schemaIndex = 2,
  )
  public val max_tokens: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val stream: Boolean = false,
  tools: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ChatConfig, Nothing>(ADAPTER, unknownFields) {
  /**
   * Available tools/functions
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 4,
  )
  public val tools: List<String> = immutableCopyOf("tools", tools)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatConfig) return false
    if (unknownFields != other.unknownFields) return false
    if (model != other.model) return false
    if (temperature != other.temperature) return false
    if (max_tokens != other.max_tokens) return false
    if (stream != other.stream) return false
    if (tools != other.tools) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + model.hashCode()
      result = result * 37 + temperature.hashCode()
      result = result * 37 + max_tokens.hashCode()
      result = result * 37 + stream.hashCode()
      result = result * 37 + tools.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """model=${sanitize(model)}"""
    result += """temperature=$temperature"""
    result += """max_tokens=$max_tokens"""
    result += """stream=$stream"""
    if (tools.isNotEmpty()) result += """tools=${sanitize(tools)}"""
    return result.joinToString(prefix = "ChatConfig{", separator = ", ", postfix = "}")
  }

  public fun copy(
    model: String = this.model,
    temperature: Float = this.temperature,
    max_tokens: Int = this.max_tokens,
    stream: Boolean = this.stream,
    tools: List<String> = this.tools,
    unknownFields: ByteString = this.unknownFields,
  ): ChatConfig = ChatConfig(model, temperature, max_tokens, stream, tools, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatConfig> = object : ProtoAdapter<ChatConfig>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatConfig::class, 
      "type.googleapis.com/com.augmentalis.rpc.ava.ChatConfig", 
      PROTO_3, 
      null, 
      "ava.proto"
    ) {
      override fun encodedSize(`value`: ChatConfig): Int {
        var size = value.unknownFields.size
        if (value.model != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.model)
        }
        if (!value.temperature.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(2, value.temperature)
        }
        if (value.max_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.max_tokens)
        }
        if (value.stream != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.stream)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(5, value.tools)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatConfig) {
        if (value.model != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.model)
        }
        if (!value.temperature.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.temperature)
        }
        if (value.max_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.max_tokens)
        }
        if (value.stream != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.stream)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 5, value.tools)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatConfig) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 5, value.tools)
        if (value.stream != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.stream)
        }
        if (value.max_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.max_tokens)
        }
        if (!value.temperature.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.temperature)
        }
        if (value.model != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.model)
        }
      }

      override fun decode(reader: ProtoReader): ChatConfig {
        var model: String = ""
        var temperature: Float = 0f
        var max_tokens: Int = 0
        var stream: Boolean = false
        val tools = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> model = ProtoAdapter.STRING.decode(reader)
            2 -> temperature = ProtoAdapter.FLOAT.decode(reader)
            3 -> max_tokens = ProtoAdapter.INT32.decode(reader)
            4 -> stream = ProtoAdapter.BOOL.decode(reader)
            5 -> tools.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatConfig(
          model = model,
          temperature = temperature,
          max_tokens = max_tokens,
          stream = stream,
          tools = tools,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatConfig): ChatConfig = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
