// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.ava.ContextData in ava.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.ava

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * Context data for RAG
 */
public class ContextData(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val source: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val content: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val relevance: Float = 0f,
  metadata: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ContextData, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 4,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 3,
  )
  public val metadata: Map<String, String> = immutableCopyOf("metadata", metadata)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ContextData) return false
    if (unknownFields != other.unknownFields) return false
    if (source != other.source) return false
    if (content != other.content) return false
    if (relevance != other.relevance) return false
    if (metadata != other.metadata) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + source.hashCode()
      result = result * 37 + content.hashCode()
      result = result * 37 + relevance.hashCode()
      result = result * 37 + metadata.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """source=${sanitize(source)}"""
    result += """content=${sanitize(content)}"""
    result += """relevance=$relevance"""
    if (metadata.isNotEmpty()) result += """metadata=$metadata"""
    return result.joinToString(prefix = "ContextData{", separator = ", ", postfix = "}")
  }

  public fun copy(
    source: String = this.source,
    content: String = this.content,
    relevance: Float = this.relevance,
    metadata: Map<String, String> = this.metadata,
    unknownFields: ByteString = this.unknownFields,
  ): ContextData = ContextData(source, content, relevance, metadata, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ContextData> = object : ProtoAdapter<ContextData>(
      FieldEncoding.LENGTH_DELIMITED, 
      ContextData::class, 
      "type.googleapis.com/com.augmentalis.rpc.ava.ContextData", 
      PROTO_3, 
      null, 
      "ava.proto"
    ) {
      private val metadataAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: ContextData): Int {
        var size = value.unknownFields.size
        if (value.source != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.source)
        }
        if (value.content != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.content)
        }
        if (!value.relevance.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(3, value.relevance)
        }
        size += metadataAdapter.encodedSizeWithTag(4, value.metadata)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ContextData) {
        if (value.source != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.source)
        }
        if (value.content != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.content)
        }
        if (!value.relevance.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.relevance)
        }
        metadataAdapter.encodeWithTag(writer, 4, value.metadata)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ContextData) {
        writer.writeBytes(value.unknownFields)
        metadataAdapter.encodeWithTag(writer, 4, value.metadata)
        if (!value.relevance.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.relevance)
        }
        if (value.content != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.content)
        }
        if (value.source != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.source)
        }
      }

      override fun decode(reader: ProtoReader): ContextData {
        var source: String = ""
        var content: String = ""
        var relevance: Float = 0f
        val metadata = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> source = ProtoAdapter.STRING.decode(reader)
            2 -> content = ProtoAdapter.STRING.decode(reader)
            3 -> relevance = ProtoAdapter.FLOAT.decode(reader)
            4 -> metadata.putAll(metadataAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ContextData(
          source = source,
          content = content,
          relevance = relevance,
          metadata = metadata,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ContextData): ContextData = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
