package com.augmentalis.voiceavanue.models

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Voice Command entity for cross-process communication.
 * Maps to Room VoiceCommand entity internally.
 *
 * @property id Unique command identifier
 * @property command Voice command text (e.g., "open email")
 * @property action Action to execute (e.g., "com.example.OPEN_EMAIL")
 * @property category Command category (e.g., "navigation", "system")
 * @property enabled Whether command is currently enabled
 * @property usageCount Number of times command has been used
 *
 * @author Manoj Jhawar, manoj@ideahq.net
 * @version 1.0.0
 */
@Parcelize
data class VoiceCommand(
    val id: Int,
    val command: String,
    val action: String,
    val category: String,
    val enabled: Boolean = true,
    val usageCount: Int = 0
) : Parcelable {

    companion object {
        /**
         * Create empty voice command for testing.
         */
        fun empty() = VoiceCommand(
            id = 0,
            command = "",
            action = "",
            category = "",
            enabled = true,
            usageCount = 0
        )

        /**
         * Create new voice command.
         *
         * @param command Voice command text
         * @param action Action to execute
         * @param category Command category
         * @return VoiceCommand instance ready for insertion
         */
        fun createNew(command: String, action: String, category: String) = VoiceCommand(
            id = 0, // Auto-generated by database
            command = command,
            action = action,
            category = category,
            enabled = true,
            usageCount = 0
        )
    }
}
