// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.vuid.VUIDCreatorService in vuid.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.vuid

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcStreamingCall
import com.squareup.wire.Service
import kotlin.Suppress

/**
 * Service definition
 */
public interface VUIDCreatorServiceClient : Service {
  /**
   * Query element by various criteria
   */
  public fun QueryElement(): GrpcCall<ElementQueryRequest, VUIDCommandResult>

  /**
   * Scrape current screen
   */
  public fun ScrapeScreen(): GrpcCall<ScrapeRequest, ScrapeResponse>

  /**
   * Execute action on element
   */
  public fun ExecuteAction(): GrpcCall<ElementActionRequest, VUIDCommandResult>

  /**
   * Generate VUID for element
   */
  public fun GenerateVUID(): GrpcCall<GenerateVUIDRequest, VUIDCommandResult>

  /**
   * Stream screen changes
   */
  public fun StreamScreenChanges(): GrpcStreamingCall<StreamScreenRequest, ScrapeResponse>
}
