# SwiftLint Configuration for AvaElements iOS Renderer
# Version: 1.0.0

# Included paths
included:
  - src
  - Tests

# Excluded paths
excluded:
  - .build
  - .swiftpm
  - Tests/__Snapshots__
  - Tests/__Failures__
  - Tests/Fixtures

# Enabled rules
opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - comment_spacing

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - ID
    - URL

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - x
    - y
    - z
    - dx
    - dy
    - r
    - g
    - b
    - a

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level: 2
  statement_level: 5

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

file_header:
  required_pattern: |
                    \/\/
                    \/\/ .*?\.swift
                    \/\/ AvaElements iOS Renderer
                    \/\/
                    \/\/ Created on \d{4}-\d{2}-\d{2}
                    \/\/ Copyright © \d{4} Augmentalis\. All rights reserved\.
                    \/\/

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '\bprint\('
    message: "Use proper logging instead of print()"
    severity: warning

  no_force_unwrap:
    name: "No Force Unwrap in Production Code"
    regex: '!\s*(?!\=)'
    match_kinds:
      - identifier
    excluded: "Tests/**"
    message: "Avoid force unwrapping. Use guard let or if let instead."
    severity: warning

  no_nslog:
    name: "No NSLog"
    regex: '\bNSLog\('
    message: "Use proper logging instead of NSLog()"
    severity: error

  component_naming:
    name: "Component Naming Convention"
    regex: 'struct\s+(?!.*Component)[A-Z][a-zA-Z]+(?:View|Button|Text|Image|Container|Layout|Input|Checkbox|Radio|Switch|Slider|Progress|Dialog|Sheet|Popup|Menu|List|Grid|Card|AppBar|NavigationBar|TabBar|Drawer|Scaffold|Form|DatePicker|TimePicker|Chip|Badge|Avatar|Divider|Spacer|Icon|Loading|Animation|Gesture|Effect)\b'
    message: "Component structs should have 'Component' suffix or be in allowed view types"
    severity: warning

  test_naming:
    name: "Test Naming Convention"
    regex: 'func\s+test[A-Z][a-zA-Z_]*\('
    included: "Tests/**"
    message: "Test methods should start with 'test' followed by descriptive name"
    severity: warning

# Reporter type
reporter: "xcode"

# Strict mode (warnings treated as errors)
strict: false

# Analyzer rules (requires full build)
analyzer_rules:
  - unused_declaration
  - unused_import
