// filename: Modules/AVA/core/Domain/src/commonMain/kotlin/com/augmentalis/ava/core/domain/usecase/TeachIntentUseCase.kt
// created: 2025-12-18
// author: AVA AI Team
// © Augmentalis Inc, Intelligent Devices LLC

package com.augmentalis.ava.core.domain.usecase

import com.augmentalis.ava.core.common.Result
import com.augmentalis.ava.core.domain.model.TrainExample
import com.augmentalis.ava.core.domain.model.TrainExampleSource
import com.augmentalis.ava.core.domain.repository.TrainExampleRepository

/**
 * Use case for teaching AVA new intents through training examples.
 *
 * Responsibilities:
 * - Validate training example data
 * - Generate hash for deduplication
 * - Create training example entity
 * - Persist to repository
 * - Handle duplicate detection
 *
 * Single Responsibility: Orchestrates teaching/training logic
 */
class TeachIntentUseCase(
    private val trainExampleRepository: TrainExampleRepository
) {

    /**
     * Teach AVA a new intent with an example utterance
     *
     * @param utterance Example user input
     * @param intent Target intent classification
     * @param locale Language/region (default "en-US")
     * @param source How this example was created (MANUAL, AUTO_LEARN, CORRECTION)
     * @return Result containing the created training example or error if duplicate
     */
    suspend operator fun invoke(
        utterance: String,
        intent: String,
        locale: String = "en-US",
        source: TrainExampleSource = TrainExampleSource.MANUAL
    ): Result<TrainExample> {
        try {
            // Validate inputs
            if (utterance.isBlank()) {
                return Result.Error(
                    exception = IllegalArgumentException("Utterance cannot be blank"),
                    message = "Utterance cannot be blank"
                )
            }

            if (intent.isBlank()) {
                return Result.Error(
                    exception = IllegalArgumentException("Intent cannot be blank"),
                    message = "Intent cannot be blank"
                )
            }

            // Generate hash for deduplication
            val exampleHash = generateExampleHash(utterance, intent)

            // Check for duplicates
            val duplicateCheck = trainExampleRepository.findDuplicate(exampleHash)
            if (duplicateCheck is Result.Success && duplicateCheck.data != null) {
                return Result.Error(
                    exception = IllegalStateException("Duplicate training example"),
                    message = "This training example already exists"
                )
            }

            // Create training example
            val trainExample = TrainExample(
                id = 0, // Auto-generated by repository
                exampleHash = exampleHash,
                utterance = utterance.trim(),
                intent = intent.trim(),
                locale = locale,
                source = source,
                createdAt = System.currentTimeMillis(),
                usageCount = 0,
                lastUsed = null
            )

            // Persist to repository
            return trainExampleRepository.addTrainExample(trainExample)

        } catch (e: Exception) {
            return Result.Error(
                exception = e,
                message = "Failed to teach intent: ${e.message}"
            )
        }
    }

    /**
     * Generate MD5 hash for deduplication
     * Hash = MD5(normalized_utterance + intent)
     */
    private fun generateExampleHash(utterance: String, intent: String): String {
        val normalizedUtterance = utterance.lowercase().trim()
        val normalizedIntent = intent.lowercase().trim()
        val combined = "$normalizedUtterance|$normalizedIntent"

        // Simple hash implementation (platform-specific MD5 would be better)
        return combined.hashCode().toString()
    }
}
