// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.exploration.ExplorationConfig in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.exploration

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Exploration configuration
 */
public class ExplorationConfig(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "packageName",
    schemaIndex = 0,
  )
  public val package_name: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "maxDepth",
    schemaIndex = 1,
  )
  public val max_depth: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "timeoutMs",
    schemaIndex = 2,
  )
  public val timeout_ms: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "includeSystemUi",
    schemaIndex = 3,
  )
  public val include_system_ui: Boolean = false,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "learnGestures",
    schemaIndex = 4,
  )
  public val learn_gestures: Boolean = false,
  excluded_classes: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ExplorationConfig, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "excludedClasses",
    schemaIndex = 5,
  )
  public val excluded_classes: List<String> = immutableCopyOf("excluded_classes", excluded_classes)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ExplorationConfig) return false
    if (unknownFields != other.unknownFields) return false
    if (package_name != other.package_name) return false
    if (max_depth != other.max_depth) return false
    if (timeout_ms != other.timeout_ms) return false
    if (include_system_ui != other.include_system_ui) return false
    if (learn_gestures != other.learn_gestures) return false
    if (excluded_classes != other.excluded_classes) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + package_name.hashCode()
      result = result * 37 + max_depth.hashCode()
      result = result * 37 + timeout_ms.hashCode()
      result = result * 37 + include_system_ui.hashCode()
      result = result * 37 + learn_gestures.hashCode()
      result = result * 37 + excluded_classes.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """package_name=${sanitize(package_name)}"""
    result += """max_depth=$max_depth"""
    result += """timeout_ms=$timeout_ms"""
    result += """include_system_ui=$include_system_ui"""
    result += """learn_gestures=$learn_gestures"""
    if (excluded_classes.isNotEmpty()) result +=
        """excluded_classes=${sanitize(excluded_classes)}"""
    return result.joinToString(prefix = "ExplorationConfig{", separator = ", ", postfix = "}")
  }

  public fun copy(
    package_name: String = this.package_name,
    max_depth: Int = this.max_depth,
    timeout_ms: Int = this.timeout_ms,
    include_system_ui: Boolean = this.include_system_ui,
    learn_gestures: Boolean = this.learn_gestures,
    excluded_classes: List<String> = this.excluded_classes,
    unknownFields: ByteString = this.unknownFields,
  ): ExplorationConfig = ExplorationConfig(package_name, max_depth, timeout_ms, include_system_ui,
      learn_gestures, excluded_classes, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ExplorationConfig> = object : ProtoAdapter<ExplorationConfig>(
      FieldEncoding.LENGTH_DELIMITED, 
      ExplorationConfig::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.exploration.ExplorationConfig", 
      PROTO_3, 
      null, 
      "exploration.proto"
    ) {
      override fun encodedSize(`value`: ExplorationConfig): Int {
        var size = value.unknownFields.size
        if (value.package_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.package_name)
        }
        if (value.max_depth != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.max_depth)
        }
        if (value.timeout_ms != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.timeout_ms)
        }
        if (value.include_system_ui != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.include_system_ui)
        }
        if (value.learn_gestures != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(5, value.learn_gestures)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(6, value.excluded_classes)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ExplorationConfig) {
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.package_name)
        }
        if (value.max_depth != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.max_depth)
        }
        if (value.timeout_ms != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.timeout_ms)
        }
        if (value.include_system_ui != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.include_system_ui)
        }
        if (value.learn_gestures != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.learn_gestures)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 6, value.excluded_classes)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ExplorationConfig) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 6, value.excluded_classes)
        if (value.learn_gestures != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.learn_gestures)
        }
        if (value.include_system_ui != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.include_system_ui)
        }
        if (value.timeout_ms != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.timeout_ms)
        }
        if (value.max_depth != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.max_depth)
        }
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.package_name)
        }
      }

      override fun decode(reader: ProtoReader): ExplorationConfig {
        var package_name: String = ""
        var max_depth: Int = 0
        var timeout_ms: Int = 0
        var include_system_ui: Boolean = false
        var learn_gestures: Boolean = false
        val excluded_classes = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> package_name = ProtoAdapter.STRING.decode(reader)
            2 -> max_depth = ProtoAdapter.INT32.decode(reader)
            3 -> timeout_ms = ProtoAdapter.INT32.decode(reader)
            4 -> include_system_ui = ProtoAdapter.BOOL.decode(reader)
            5 -> learn_gestures = ProtoAdapter.BOOL.decode(reader)
            6 -> excluded_classes.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ExplorationConfig(
          package_name = package_name,
          max_depth = max_depth,
          timeout_ms = timeout_ms,
          include_system_ui = include_system_ui,
          learn_gestures = learn_gestures,
          excluded_classes = excluded_classes,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ExplorationConfig): ExplorationConfig = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
