// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.exploration.ExplorationState in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.exploration

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Exploration state
 */
public enum class ExplorationState(
  override val `value`: Int,
) : WireEnum {
  EXPLORATION_IDLE(0),
  EXPLORATION_CAPTURING(1),
  EXPLORATION_ANALYZING(2),
  EXPLORATION_LEARNING(3),
  EXPLORATION_COMPLETED(4),
  EXPLORATION_FAILED(5),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ExplorationState> = object : EnumAdapter<ExplorationState>(
      ExplorationState::class, 
      PROTO_3, 
      ExplorationState.EXPLORATION_IDLE
    ) {
      override fun fromValue(`value`: Int): ExplorationState? = ExplorationState.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ExplorationState? = when (`value`) {
      0 -> EXPLORATION_IDLE
      1 -> EXPLORATION_CAPTURING
      2 -> EXPLORATION_ANALYZING
      3 -> EXPLORATION_LEARNING
      4 -> EXPLORATION_COMPLETED
      5 -> EXPLORATION_FAILED
      else -> null
    }
  }
}
