// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.exploration.ExplorationService in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.exploration

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import com.squareup.wire.GrpcStreamingCall
import kotlin.Suppress

/**
 * Service definition
 */
public class GrpcExplorationServiceClient(
  private val client: GrpcClient,
) : ExplorationServiceClient {
  /**
   * Start full exploration
   */
  override fun StartExploration(): GrpcCall<StartExplorationRequest, ExplorationResult> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.exploration.ExplorationService/StartExploration",
      requestAdapter = StartExplorationRequest.ADAPTER,
      responseAdapter = ExplorationResult.ADAPTER
  ))

  /**
   * Stop current exploration
   */
  override fun StopExploration(): GrpcCall<StopExplorationRequest, ExplorationResult> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.exploration.ExplorationService/StopExploration",
      requestAdapter = StopExplorationRequest.ADAPTER,
      responseAdapter = ExplorationResult.ADAPTER
  ))

  /**
   * Get exploration progress
   */
  override fun GetProgress(): GrpcCall<GetProgressRequest, ExplorationProgress> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.exploration.ExplorationService/GetProgress",
      requestAdapter = GetProgressRequest.ADAPTER,
      responseAdapter = ExplorationProgress.ADAPTER
  ))

  /**
   * JIT learning
   */
  override fun LearnJIT(): GrpcCall<JITLearnRequest, JITLearnResult> = client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.exploration.ExplorationService/LearnJIT",
      requestAdapter = JITLearnRequest.ADAPTER,
      responseAdapter = JITLearnResult.ADAPTER
  ))

  /**
   * Capture specific element
   */
  override fun CaptureElement(): GrpcCall<CaptureElementRequest, LearnedElement> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.exploration.ExplorationService/CaptureElement",
      requestAdapter = CaptureElementRequest.ADAPTER,
      responseAdapter = LearnedElement.ADAPTER
  ))

  /**
   * Stream exploration progress
   */
  override fun StreamProgress(): GrpcStreamingCall<StartExplorationRequest, ExplorationProgress> =
      client.newStreamingCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.exploration.ExplorationService/StreamProgress",
      requestAdapter = StartExplorationRequest.ADAPTER,
      responseAdapter = ExplorationProgress.ADAPTER
  ))

  /**
   * Get learned data for app
   */
  override fun GetLearnedData(): GrpcCall<GetLearnedDataRequest, ExplorationResult> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.exploration.ExplorationService/GetLearnedData",
      requestAdapter = GetLearnedDataRequest.ADAPTER,
      responseAdapter = ExplorationResult.ADAPTER
  ))
}
