// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.exploration.StartExplorationRequest in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.exploration

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Start exploration request
 */
public class StartExplorationRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.augmentalis.universalrpc.exploration.ExplorationConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val config: ExplorationConfig? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StartExplorationRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StartExplorationRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (config != other.config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + (config?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    if (config != null) result += """config=$config"""
    return result.joinToString(prefix = "StartExplorationRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    config: ExplorationConfig? = this.config,
    unknownFields: ByteString = this.unknownFields,
  ): StartExplorationRequest = StartExplorationRequest(request_id, config, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StartExplorationRequest> = object :
        ProtoAdapter<StartExplorationRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      StartExplorationRequest::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.exploration.StartExplorationRequest", 
      PROTO_3, 
      null, 
      "exploration.proto"
    ) {
      override fun encodedSize(`value`: StartExplorationRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.config != null) {
          size += ExplorationConfig.ADAPTER.encodedSizeWithTag(2, value.config)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: StartExplorationRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.config != null) {
          ExplorationConfig.ADAPTER.encodeWithTag(writer, 2, value.config)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: StartExplorationRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.config != null) {
          ExplorationConfig.ADAPTER.encodeWithTag(writer, 2, value.config)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): StartExplorationRequest {
        var request_id: String = ""
        var config: ExplorationConfig? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> config = ExplorationConfig.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return StartExplorationRequest(
          request_id = request_id,
          config = config,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: StartExplorationRequest): StartExplorationRequest = value.copy(
        config = value.config?.let(ExplorationConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
