// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.recognition.RecognitionEvent in recognition.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.recognition

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Recognition event (streaming)
 */
public class RecognitionEvent(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sessionId",
    schemaIndex = 0,
  )
  public val session_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.augmentalis.universalrpc.recognition.RecognitionData#ADAPTER",
    oneofName = "event",
    schemaIndex = 1,
  )
  public val result: RecognitionData? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.augmentalis.universalrpc.recognition.RecognitionError#ADAPTER",
    oneofName = "event",
    schemaIndex = 2,
  )
  public val error: RecognitionError? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.augmentalis.universalrpc.recognition.RecognitionStatus#ADAPTER",
    oneofName = "event",
    schemaIndex = 3,
  )
  public val status: RecognitionStatus? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RecognitionEvent, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(result, error, status) <= 1) {
      "At most one of result, error, status may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RecognitionEvent) return false
    if (unknownFields != other.unknownFields) return false
    if (session_id != other.session_id) return false
    if (result != other.result) return false
    if (error != other.error) return false
    if (status != other.status) return false
    return true
  }

  override fun hashCode(): Int {
    var result_ = super.hashCode
    if (result_ == 0) {
      result_ = unknownFields.hashCode()
      result_ = result_ * 37 + session_id.hashCode()
      result_ = result_ * 37 + (result?.hashCode() ?: 0)
      result_ = result_ * 37 + (error?.hashCode() ?: 0)
      result_ = result_ * 37 + (status?.hashCode() ?: 0)
      super.hashCode = result_
    }
    return result_
  }

  override fun toString(): String {
    val result_ = mutableListOf<String>()
    result_ += """session_id=${sanitize(session_id)}"""
    if (result != null) result_ += """result=$result"""
    if (error != null) result_ += """error=$error"""
    if (status != null) result_ += """status=$status"""
    return result_.joinToString(prefix = "RecognitionEvent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    session_id: String = this.session_id,
    result: RecognitionData? = this.result,
    error: RecognitionError? = this.error,
    status: RecognitionStatus? = this.status,
    unknownFields: ByteString = this.unknownFields,
  ): RecognitionEvent = RecognitionEvent(session_id, result, error, status, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RecognitionEvent> = object : ProtoAdapter<RecognitionEvent>(
      FieldEncoding.LENGTH_DELIMITED, 
      RecognitionEvent::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.recognition.RecognitionEvent", 
      PROTO_3, 
      null, 
      "recognition.proto"
    ) {
      override fun encodedSize(`value`: RecognitionEvent): Int {
        var size = value.unknownFields.size
        if (value.session_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.session_id)
        }
        size += RecognitionData.ADAPTER.encodedSizeWithTag(2, value.result)
        size += RecognitionError.ADAPTER.encodedSizeWithTag(3, value.error)
        size += RecognitionStatus.ADAPTER.encodedSizeWithTag(4, value.status)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RecognitionEvent) {
        if (value.session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.session_id)
        }
        RecognitionData.ADAPTER.encodeWithTag(writer, 2, value.result)
        RecognitionError.ADAPTER.encodeWithTag(writer, 3, value.error)
        RecognitionStatus.ADAPTER.encodeWithTag(writer, 4, value.status)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RecognitionEvent) {
        writer.writeBytes(value.unknownFields)
        RecognitionStatus.ADAPTER.encodeWithTag(writer, 4, value.status)
        RecognitionError.ADAPTER.encodeWithTag(writer, 3, value.error)
        RecognitionData.ADAPTER.encodeWithTag(writer, 2, value.result)
        if (value.session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.session_id)
        }
      }

      override fun decode(reader: ProtoReader): RecognitionEvent {
        var session_id: String = ""
        var result: RecognitionData? = null
        var error: RecognitionError? = null
        var status: RecognitionStatus? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> session_id = ProtoAdapter.STRING.decode(reader)
            2 -> result = RecognitionData.ADAPTER.decode(reader)
            3 -> error = RecognitionError.ADAPTER.decode(reader)
            4 -> status = RecognitionStatus.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RecognitionEvent(
          session_id = session_id,
          result = result,
          error = error,
          status = status,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RecognitionEvent): RecognitionEvent = value.copy(
        result = value.result?.let(RecognitionData.ADAPTER::redact),
        error = value.error?.let(RecognitionError.ADAPTER::redact),
        status = value.status?.let(RecognitionStatus.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
