// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.webavanue.ElementSelector in webavanue.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.webavanue

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Element selector
 */
public class ElementSelector(
  /**
   * CSS selector
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val css: String = "",
  /**
   * XPath selector
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val xpath: String = "",
  /**
   * Text content match
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val text: String = "",
  /**
   * VUID if available
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val avid: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ElementSelector, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ElementSelector) return false
    if (unknownFields != other.unknownFields) return false
    if (css != other.css) return false
    if (xpath != other.xpath) return false
    if (text != other.text) return false
    if (avid != other.avid) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + css.hashCode()
      result = result * 37 + xpath.hashCode()
      result = result * 37 + text.hashCode()
      result = result * 37 + avid.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """css=${sanitize(css)}"""
    result += """xpath=${sanitize(xpath)}"""
    result += """text=${sanitize(text)}"""
    result += """avid=${sanitize(avid)}"""
    return result.joinToString(prefix = "ElementSelector{", separator = ", ", postfix = "}")
  }

  public fun copy(
    css: String = this.css,
    xpath: String = this.xpath,
    text: String = this.text,
    avid: String = this.avid,
    unknownFields: ByteString = this.unknownFields,
  ): ElementSelector = ElementSelector(css, xpath, text, avid, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ElementSelector> = object : ProtoAdapter<ElementSelector>(
      FieldEncoding.LENGTH_DELIMITED, 
      ElementSelector::class, 
      "type.googleapis.com/com.augmentalis.rpc.webavanue.ElementSelector", 
      PROTO_3, 
      null, 
      "webavanue.proto"
    ) {
      override fun encodedSize(`value`: ElementSelector): Int {
        var size = value.unknownFields.size
        if (value.css != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.css)
        }
        if (value.xpath != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.xpath)
        }
        if (value.text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.text)
        }
        if (value.avid != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.avid)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ElementSelector) {
        if (value.css != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.css)
        }
        if (value.xpath != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.xpath)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.text)
        }
        if (value.avid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.avid)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ElementSelector) {
        writer.writeBytes(value.unknownFields)
        if (value.avid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.avid)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.text)
        }
        if (value.xpath != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.xpath)
        }
        if (value.css != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.css)
        }
      }

      override fun decode(reader: ProtoReader): ElementSelector {
        var css: String = ""
        var xpath: String = ""
        var text: String = ""
        var avid: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> css = ProtoAdapter.STRING.decode(reader)
            2 -> xpath = ProtoAdapter.STRING.decode(reader)
            3 -> text = ProtoAdapter.STRING.decode(reader)
            4 -> avid = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ElementSelector(
          css = css,
          xpath = xpath,
          text = text,
          avid = avid,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ElementSelector): ElementSelector = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
