// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.webavanue.PageElement in webavanue.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.webavanue

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * Page element
 */
public class PageElement(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "elementId",
    schemaIndex = 0,
  )
  public val element_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val tag: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val text: String = "",
  attributes: Map<String, String> = emptyMap(),
  @field:WireField(
    tag = 5,
    adapter = "com.augmentalis.rpc.webavanue.Rect#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val bounds: Rect? = null,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val visible: Boolean = false,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val interactable: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PageElement, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 4,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 3,
  )
  public val attributes: Map<String, String> = immutableCopyOf("attributes", attributes)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PageElement) return false
    if (unknownFields != other.unknownFields) return false
    if (element_id != other.element_id) return false
    if (tag != other.tag) return false
    if (text != other.text) return false
    if (attributes != other.attributes) return false
    if (bounds != other.bounds) return false
    if (visible != other.visible) return false
    if (interactable != other.interactable) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + element_id.hashCode()
      result = result * 37 + tag.hashCode()
      result = result * 37 + text.hashCode()
      result = result * 37 + attributes.hashCode()
      result = result * 37 + (bounds?.hashCode() ?: 0)
      result = result * 37 + visible.hashCode()
      result = result * 37 + interactable.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """element_id=${sanitize(element_id)}"""
    result += """tag=${sanitize(tag)}"""
    result += """text=${sanitize(text)}"""
    if (attributes.isNotEmpty()) result += """attributes=$attributes"""
    if (bounds != null) result += """bounds=$bounds"""
    result += """visible=$visible"""
    result += """interactable=$interactable"""
    return result.joinToString(prefix = "PageElement{", separator = ", ", postfix = "}")
  }

  public fun copy(
    element_id: String = this.element_id,
    tag: String = this.tag,
    text: String = this.text,
    attributes: Map<String, String> = this.attributes,
    bounds: Rect? = this.bounds,
    visible: Boolean = this.visible,
    interactable: Boolean = this.interactable,
    unknownFields: ByteString = this.unknownFields,
  ): PageElement = PageElement(element_id, tag, text, attributes, bounds, visible, interactable,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PageElement> = object : ProtoAdapter<PageElement>(
      FieldEncoding.LENGTH_DELIMITED, 
      PageElement::class, 
      "type.googleapis.com/com.augmentalis.rpc.webavanue.PageElement", 
      PROTO_3, 
      null, 
      "webavanue.proto"
    ) {
      private val attributesAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: PageElement): Int {
        var size = value.unknownFields.size
        if (value.element_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.element_id)
        }
        if (value.tag != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.tag)
        }
        if (value.text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.text)
        }
        size += attributesAdapter.encodedSizeWithTag(4, value.attributes)
        if (value.bounds != null) {
          size += Rect.ADAPTER.encodedSizeWithTag(5, value.bounds)
        }
        if (value.visible != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(6, value.visible)
        }
        if (value.interactable != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(7, value.interactable)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PageElement) {
        if (value.element_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.element_id)
        }
        if (value.tag != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.tag)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.text)
        }
        attributesAdapter.encodeWithTag(writer, 4, value.attributes)
        if (value.bounds != null) {
          Rect.ADAPTER.encodeWithTag(writer, 5, value.bounds)
        }
        if (value.visible != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.visible)
        }
        if (value.interactable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.interactable)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PageElement) {
        writer.writeBytes(value.unknownFields)
        if (value.interactable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.interactable)
        }
        if (value.visible != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.visible)
        }
        if (value.bounds != null) {
          Rect.ADAPTER.encodeWithTag(writer, 5, value.bounds)
        }
        attributesAdapter.encodeWithTag(writer, 4, value.attributes)
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.text)
        }
        if (value.tag != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.tag)
        }
        if (value.element_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.element_id)
        }
      }

      override fun decode(reader: ProtoReader): PageElement {
        var element_id: String = ""
        var tag: String = ""
        var text: String = ""
        val attributes = mutableMapOf<String, String>()
        var bounds: Rect? = null
        var visible: Boolean = false
        var interactable: Boolean = false
        val unknownFields = reader.forEachTag { tag_ ->
          when (tag_) {
            1 -> element_id = ProtoAdapter.STRING.decode(reader)
            2 -> tag = ProtoAdapter.STRING.decode(reader)
            3 -> text = ProtoAdapter.STRING.decode(reader)
            4 -> attributes.putAll(attributesAdapter.decode(reader))
            5 -> bounds = Rect.ADAPTER.decode(reader)
            6 -> visible = ProtoAdapter.BOOL.decode(reader)
            7 -> interactable = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag_)
          }
        }
        return PageElement(
          element_id = element_id,
          tag = tag,
          text = text,
          attributes = attributes,
          bounds = bounds,
          visible = visible,
          interactable = interactable,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PageElement): PageElement = value.copy(
        bounds = value.bounds?.let(Rect.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
