// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.nlu.ModelsResponse in nlu.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.nlu

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class ModelsResponse(
  models: List<ModelInfo> = emptyList(),
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "defaultModel",
    schemaIndex = 1,
  )
  public val default_model: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ModelsResponse, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.augmentalis.universalrpc.nlu.ModelInfo#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val models: List<ModelInfo> = immutableCopyOf("models", models)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ModelsResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (models != other.models) return false
    if (default_model != other.default_model) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + models.hashCode()
      result = result * 37 + default_model.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (models.isNotEmpty()) result += """models=$models"""
    result += """default_model=${sanitize(default_model)}"""
    return result.joinToString(prefix = "ModelsResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    models: List<ModelInfo> = this.models,
    default_model: String = this.default_model,
    unknownFields: ByteString = this.unknownFields,
  ): ModelsResponse = ModelsResponse(models, default_model, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ModelsResponse> = object : ProtoAdapter<ModelsResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ModelsResponse::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.nlu.ModelsResponse", 
      PROTO_3, 
      null, 
      "nlu.proto"
    ) {
      override fun encodedSize(`value`: ModelsResponse): Int {
        var size = value.unknownFields.size
        size += ModelInfo.ADAPTER.asRepeated().encodedSizeWithTag(1, value.models)
        if (value.default_model != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.default_model)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ModelsResponse) {
        ModelInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.models)
        if (value.default_model != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.default_model)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ModelsResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.default_model != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.default_model)
        }
        ModelInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.models)
      }

      override fun decode(reader: ProtoReader): ModelsResponse {
        val models = mutableListOf<ModelInfo>()
        var default_model: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> models.add(ModelInfo.ADAPTER.decode(reader))
            2 -> default_model = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ModelsResponse(
          models = models,
          default_model = default_model,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ModelsResponse): ModelsResponse = value.copy(
        models = value.models.redactElements(ModelInfo.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
