// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.nlu.NLUService in nlu.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.nlu

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import kotlin.Suppress

/**
 * Service definition
 */
public interface NLUServiceClient : Service {
  /**
   * Classify intent
   */
  public fun Classify(): GrpcCall<ClassifyRequest, ClassifyResponse>

  /**
   * Extract entities
   */
  public fun ExtractEntities(): GrpcCall<ExtractEntitiesRequest, ExtractEntitiesResponse>

  /**
   * Parse voice command
   */
  public fun ParseCommand(): GrpcCall<ParseCommandRequest, ParsedCommand>

  /**
   * Batch classify
   */
  public fun BatchClassify(): GrpcCall<BatchClassifyRequest, BatchClassifyResponse>

  /**
   * Get available models
   */
  public fun GetModels(): GrpcCall<GetModelsRequest, ModelsResponse>
}
