// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.nlu.ParseCommandRequest in nlu.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.nlu

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Command parsing request
 */
public class ParseCommandRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val text: String = "",
  /**
   * Current app package
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "contextPackage",
    schemaIndex = 2,
  )
  public val context_package: String = "",
  /**
   * Current activity
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "contextActivity",
    schemaIndex = 3,
  )
  public val context_activity: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ParseCommandRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ParseCommandRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (text != other.text) return false
    if (context_package != other.context_package) return false
    if (context_activity != other.context_activity) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + text.hashCode()
      result = result * 37 + context_package.hashCode()
      result = result * 37 + context_activity.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """text=${sanitize(text)}"""
    result += """context_package=${sanitize(context_package)}"""
    result += """context_activity=${sanitize(context_activity)}"""
    return result.joinToString(prefix = "ParseCommandRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    text: String = this.text,
    context_package: String = this.context_package,
    context_activity: String = this.context_activity,
    unknownFields: ByteString = this.unknownFields,
  ): ParseCommandRequest = ParseCommandRequest(request_id, text, context_package, context_activity,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ParseCommandRequest> = object :
        ProtoAdapter<ParseCommandRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      ParseCommandRequest::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.nlu.ParseCommandRequest", 
      PROTO_3, 
      null, 
      "nlu.proto"
    ) {
      override fun encodedSize(`value`: ParseCommandRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.text)
        }
        if (value.context_package != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.context_package)
        }
        if (value.context_activity != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.context_activity)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ParseCommandRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.text)
        }
        if (value.context_package != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.context_package)
        }
        if (value.context_activity != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.context_activity)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ParseCommandRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.context_activity != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.context_activity)
        }
        if (value.context_package != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.context_package)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.text)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): ParseCommandRequest {
        var request_id: String = ""
        var text: String = ""
        var context_package: String = ""
        var context_activity: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> text = ProtoAdapter.STRING.decode(reader)
            3 -> context_package = ProtoAdapter.STRING.decode(reader)
            4 -> context_activity = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ParseCommandRequest(
          request_id = request_id,
          text = text,
          context_package = context_package,
          context_activity = context_activity,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ParseCommandRequest): ParseCommandRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
