// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.cursor.CursorConfig in cursor.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.cursor

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Cursor configuration
 */
public class CursorConfig(
  /**
   * Cursor size in dp
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val size: Int = 0,
  /**
   * ARGB color value
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val color: Int = 0,
  /**
   * Movement speed multiplier
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val speed: Float = 0f,
  /**
   * Visibility state
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val visible: Boolean = false,
  /**
   * Mode: "gaze", "touch", "voice"
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val mode: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<CursorConfig, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CursorConfig) return false
    if (unknownFields != other.unknownFields) return false
    if (size != other.size) return false
    if (color != other.color) return false
    if (speed != other.speed) return false
    if (visible != other.visible) return false
    if (mode != other.mode) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + size.hashCode()
      result = result * 37 + color.hashCode()
      result = result * 37 + speed.hashCode()
      result = result * 37 + visible.hashCode()
      result = result * 37 + mode.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """size=$size"""
    result += """color=$color"""
    result += """speed=$speed"""
    result += """visible=$visible"""
    result += """mode=${sanitize(mode)}"""
    return result.joinToString(prefix = "CursorConfig{", separator = ", ", postfix = "}")
  }

  public fun copy(
    size: Int = this.size,
    color: Int = this.color,
    speed: Float = this.speed,
    visible: Boolean = this.visible,
    mode: String = this.mode,
    unknownFields: ByteString = this.unknownFields,
  ): CursorConfig = CursorConfig(size, color, speed, visible, mode, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CursorConfig> = object : ProtoAdapter<CursorConfig>(
      FieldEncoding.LENGTH_DELIMITED, 
      CursorConfig::class, 
      "type.googleapis.com/com.augmentalis.rpc.cursor.CursorConfig", 
      PROTO_3, 
      null, 
      "cursor.proto"
    ) {
      override fun encodedSize(`value`: CursorConfig): Int {
        var size_ = value.unknownFields.size
        if (value.size != 0) {
          size_ += ProtoAdapter.INT32.encodedSizeWithTag(1, value.size)
        }
        if (value.color != 0) {
          size_ += ProtoAdapter.INT32.encodedSizeWithTag(2, value.color)
        }
        if (!value.speed.equals(0f)) {
          size_ += ProtoAdapter.FLOAT.encodedSizeWithTag(3, value.speed)
        }
        if (value.visible != false) {
          size_ += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.visible)
        }
        if (value.mode != "") {
          size_ += ProtoAdapter.STRING.encodedSizeWithTag(5, value.mode)
        }
        return size_
      }

      override fun encode(writer: ProtoWriter, `value`: CursorConfig) {
        if (value.size != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.size)
        }
        if (value.color != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.color)
        }
        if (!value.speed.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.speed)
        }
        if (value.visible != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.visible)
        }
        if (value.mode != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.mode)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: CursorConfig) {
        writer.writeBytes(value.unknownFields)
        if (value.mode != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.mode)
        }
        if (value.visible != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.visible)
        }
        if (!value.speed.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.speed)
        }
        if (value.color != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.color)
        }
        if (value.size != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.size)
        }
      }

      override fun decode(reader: ProtoReader): CursorConfig {
        var size: Int = 0
        var color: Int = 0
        var speed: Float = 0f
        var visible: Boolean = false
        var mode: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> size = ProtoAdapter.INT32.decode(reader)
            2 -> color = ProtoAdapter.INT32.decode(reader)
            3 -> speed = ProtoAdapter.FLOAT.decode(reader)
            4 -> visible = ProtoAdapter.BOOL.decode(reader)
            5 -> mode = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CursorConfig(
          size = size,
          color = color,
          speed = speed,
          visible = visible,
          mode = mode,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: CursorConfig): CursorConfig = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
