// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.cursor.MoveCursorRequest in cursor.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.cursor

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Cursor movement request
 */
public class MoveCursorRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "targetX",
    schemaIndex = 1,
  )
  public val target_x: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "targetY",
    schemaIndex = 2,
  )
  public val target_y: Int = 0,
  /**
   * Smooth animation
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val animate: Boolean = false,
  /**
   * Animation duration
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "durationMs",
    schemaIndex = 4,
  )
  public val duration_ms: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MoveCursorRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MoveCursorRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (target_x != other.target_x) return false
    if (target_y != other.target_y) return false
    if (animate != other.animate) return false
    if (duration_ms != other.duration_ms) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + target_x.hashCode()
      result = result * 37 + target_y.hashCode()
      result = result * 37 + animate.hashCode()
      result = result * 37 + duration_ms.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """target_x=$target_x"""
    result += """target_y=$target_y"""
    result += """animate=$animate"""
    result += """duration_ms=$duration_ms"""
    return result.joinToString(prefix = "MoveCursorRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    target_x: Int = this.target_x,
    target_y: Int = this.target_y,
    animate: Boolean = this.animate,
    duration_ms: Int = this.duration_ms,
    unknownFields: ByteString = this.unknownFields,
  ): MoveCursorRequest = MoveCursorRequest(request_id, target_x, target_y, animate, duration_ms,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MoveCursorRequest> = object : ProtoAdapter<MoveCursorRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      MoveCursorRequest::class, 
      "type.googleapis.com/com.augmentalis.rpc.cursor.MoveCursorRequest", 
      PROTO_3, 
      null, 
      "cursor.proto"
    ) {
      override fun encodedSize(`value`: MoveCursorRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.target_x != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.target_x)
        }
        if (value.target_y != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.target_y)
        }
        if (value.animate != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.animate)
        }
        if (value.duration_ms != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.duration_ms)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: MoveCursorRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.target_x != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.target_x)
        }
        if (value.target_y != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.target_y)
        }
        if (value.animate != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.animate)
        }
        if (value.duration_ms != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.duration_ms)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MoveCursorRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.duration_ms != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.duration_ms)
        }
        if (value.animate != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.animate)
        }
        if (value.target_y != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.target_y)
        }
        if (value.target_x != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.target_x)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): MoveCursorRequest {
        var request_id: String = ""
        var target_x: Int = 0
        var target_y: Int = 0
        var animate: Boolean = false
        var duration_ms: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> target_x = ProtoAdapter.INT32.decode(reader)
            3 -> target_y = ProtoAdapter.INT32.decode(reader)
            4 -> animate = ProtoAdapter.BOOL.decode(reader)
            5 -> duration_ms = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MoveCursorRequest(
          request_id = request_id,
          target_x = target_x,
          target_y = target_y,
          animate = animate,
          duration_ms = duration_ms,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MoveCursorRequest): MoveCursorRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
