// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.cursor.StreamPositionRequest in cursor.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.cursor

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class StreamPositionRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  /**
   * Update interval in ms
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "intervalMs",
    schemaIndex = 1,
  )
  public val interval_ms: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StreamPositionRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StreamPositionRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (interval_ms != other.interval_ms) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + interval_ms.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """interval_ms=$interval_ms"""
    return result.joinToString(prefix = "StreamPositionRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    interval_ms: Int = this.interval_ms,
    unknownFields: ByteString = this.unknownFields,
  ): StreamPositionRequest = StreamPositionRequest(request_id, interval_ms, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StreamPositionRequest> = object :
        ProtoAdapter<StreamPositionRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      StreamPositionRequest::class, 
      "type.googleapis.com/com.augmentalis.rpc.cursor.StreamPositionRequest", 
      PROTO_3, 
      null, 
      "cursor.proto"
    ) {
      override fun encodedSize(`value`: StreamPositionRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.interval_ms != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.interval_ms)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: StreamPositionRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.interval_ms != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.interval_ms)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: StreamPositionRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.interval_ms != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.interval_ms)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): StreamPositionRequest {
        var request_id: String = ""
        var interval_ms: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> interval_ms = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return StreamPositionRequest(
          request_id = request_id,
          interval_ms = interval_ms,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: StreamPositionRequest): StreamPositionRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
