// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.cursor.VoiceCursorService in cursor.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.cursor

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcStreamingCall
import com.squareup.wire.Service
import kotlin.Suppress

/**
 * Service definition
 */
public interface VoiceCursorServiceClient : Service {
  /**
   * Get current cursor position
   */
  public fun GetPosition(): GrpcCall<GetPositionRequest, CursorPosition>

  /**
   * Move cursor to position
   */
  public fun MoveTo(): GrpcCall<MoveCursorRequest, CursorResponse>

  /**
   * Execute cursor action
   */
  public fun ExecuteAction(): GrpcCall<CursorActionRequest, CursorResponse>

  /**
   * Update cursor configuration
   */
  public fun Configure(): GrpcCall<CursorConfig, CursorResponse>

  /**
   * Stream cursor position updates
   */
  public fun StreamPosition(): GrpcStreamingCall<StreamPositionRequest, CursorPosition>
}
