// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.cursor.CursorPosition in cursor.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.cursor

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Cursor position on screen
 */
public class CursorPosition(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val x: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val y: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val timestamp: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<CursorPosition, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CursorPosition) return false
    if (unknownFields != other.unknownFields) return false
    if (x != other.x) return false
    if (y != other.y) return false
    if (timestamp != other.timestamp) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + x.hashCode()
      result = result * 37 + y.hashCode()
      result = result * 37 + timestamp.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """x=$x"""
    result += """y=$y"""
    result += """timestamp=$timestamp"""
    return result.joinToString(prefix = "CursorPosition{", separator = ", ", postfix = "}")
  }

  public fun copy(
    x: Int = this.x,
    y: Int = this.y,
    timestamp: Long = this.timestamp,
    unknownFields: ByteString = this.unknownFields,
  ): CursorPosition = CursorPosition(x, y, timestamp, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CursorPosition> = object : ProtoAdapter<CursorPosition>(
      FieldEncoding.LENGTH_DELIMITED, 
      CursorPosition::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.cursor.CursorPosition", 
      PROTO_3, 
      null, 
      "cursor.proto"
    ) {
      override fun encodedSize(`value`: CursorPosition): Int {
        var size = value.unknownFields.size
        if (value.x != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.x)
        }
        if (value.y != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.y)
        }
        if (value.timestamp != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(3, value.timestamp)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: CursorPosition) {
        if (value.x != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.x)
        }
        if (value.y != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.y)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 3, value.timestamp)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: CursorPosition) {
        writer.writeBytes(value.unknownFields)
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 3, value.timestamp)
        }
        if (value.y != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.y)
        }
        if (value.x != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.x)
        }
      }

      override fun decode(reader: ProtoReader): CursorPosition {
        var x: Int = 0
        var y: Int = 0
        var timestamp: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> x = ProtoAdapter.INT32.decode(reader)
            2 -> y = ProtoAdapter.INT32.decode(reader)
            3 -> timestamp = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CursorPosition(
          x = x,
          y = y,
          timestamp = timestamp,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: CursorPosition): CursorPosition = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
