// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.voiceos.AccessibilityActionRequest in voiceos.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.voiceos

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * Accessibility action request
 */
public class AccessibilityActionRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  /**
   * "back", "home", "recent", "notifications"
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "actionType",
    schemaIndex = 1,
  )
  public val action_type: String = "",
  params: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<AccessibilityActionRequest, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 3,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val params: Map<String, String> = immutableCopyOf("params", params)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AccessibilityActionRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (action_type != other.action_type) return false
    if (params != other.params) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + action_type.hashCode()
      result = result * 37 + params.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """action_type=${sanitize(action_type)}"""
    if (params.isNotEmpty()) result += """params=$params"""
    return result.joinToString(prefix = "AccessibilityActionRequest{", separator = ", ", postfix =
        "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    action_type: String = this.action_type,
    params: Map<String, String> = this.params,
    unknownFields: ByteString = this.unknownFields,
  ): AccessibilityActionRequest = AccessibilityActionRequest(request_id, action_type, params,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AccessibilityActionRequest> = object :
        ProtoAdapter<AccessibilityActionRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      AccessibilityActionRequest::class, 
      "type.googleapis.com/com.augmentalis.rpc.voiceos.AccessibilityActionRequest", 
      PROTO_3, 
      null, 
      "voiceos.proto"
    ) {
      private val paramsAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: AccessibilityActionRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.action_type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.action_type)
        }
        size += paramsAdapter.encodedSizeWithTag(3, value.params)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AccessibilityActionRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.action_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.action_type)
        }
        paramsAdapter.encodeWithTag(writer, 3, value.params)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AccessibilityActionRequest) {
        writer.writeBytes(value.unknownFields)
        paramsAdapter.encodeWithTag(writer, 3, value.params)
        if (value.action_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.action_type)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): AccessibilityActionRequest {
        var request_id: String = ""
        var action_type: String = ""
        val params = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> action_type = ProtoAdapter.STRING.decode(reader)
            3 -> params.putAll(paramsAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return AccessibilityActionRequest(
          request_id = request_id,
          action_type = action_type,
          params = params,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AccessibilityActionRequest): AccessibilityActionRequest =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
