// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.webavanue.Rect in webavanue.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.webavanue

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class Rect(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val x: Float = 0f,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val y: Float = 0f,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val width: Float = 0f,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val height: Float = 0f,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Rect, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Rect) return false
    if (unknownFields != other.unknownFields) return false
    if (x != other.x) return false
    if (y != other.y) return false
    if (width != other.width) return false
    if (height != other.height) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + x.hashCode()
      result = result * 37 + y.hashCode()
      result = result * 37 + width.hashCode()
      result = result * 37 + height.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """x=$x"""
    result += """y=$y"""
    result += """width=$width"""
    result += """height=$height"""
    return result.joinToString(prefix = "Rect{", separator = ", ", postfix = "}")
  }

  public fun copy(
    x: Float = this.x,
    y: Float = this.y,
    width: Float = this.width,
    height: Float = this.height,
    unknownFields: ByteString = this.unknownFields,
  ): Rect = Rect(x, y, width, height, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Rect> = object : ProtoAdapter<Rect>(
      FieldEncoding.LENGTH_DELIMITED, 
      Rect::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.webavanue.Rect", 
      PROTO_3, 
      null, 
      "webavanue.proto"
    ) {
      override fun encodedSize(`value`: Rect): Int {
        var size = value.unknownFields.size
        if (!value.x.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(1, value.x)
        }
        if (!value.y.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(2, value.y)
        }
        if (!value.width.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(3, value.width)
        }
        if (!value.height.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(4, value.height)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Rect) {
        if (!value.x.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 1, value.x)
        }
        if (!value.y.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.y)
        }
        if (!value.width.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.width)
        }
        if (!value.height.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.height)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Rect) {
        writer.writeBytes(value.unknownFields)
        if (!value.height.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.height)
        }
        if (!value.width.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.width)
        }
        if (!value.y.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.y)
        }
        if (!value.x.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 1, value.x)
        }
      }

      override fun decode(reader: ProtoReader): Rect {
        var x: Float = 0f
        var y: Float = 0f
        var width: Float = 0f
        var height: Float = 0f
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> x = ProtoAdapter.FLOAT.decode(reader)
            2 -> y = ProtoAdapter.FLOAT.decode(reader)
            3 -> width = ProtoAdapter.FLOAT.decode(reader)
            4 -> height = ProtoAdapter.FLOAT.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Rect(
          x = x,
          y = y,
          width = width,
          height = height,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Rect): Rect = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
