// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.nlu.BatchClassifyRequest in nlu.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.nlu

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class BatchClassifyRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  texts: List<String> = emptyList(),
  @field:WireField(
    tag = 3,
    adapter = "com.augmentalis.rpc.nlu.ClassifyConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val config: ClassifyConfig? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<BatchClassifyRequest, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val texts: List<String> = immutableCopyOf("texts", texts)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BatchClassifyRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (texts != other.texts) return false
    if (config != other.config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + texts.hashCode()
      result = result * 37 + (config?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    if (texts.isNotEmpty()) result += """texts=${sanitize(texts)}"""
    if (config != null) result += """config=$config"""
    return result.joinToString(prefix = "BatchClassifyRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    texts: List<String> = this.texts,
    config: ClassifyConfig? = this.config,
    unknownFields: ByteString = this.unknownFields,
  ): BatchClassifyRequest = BatchClassifyRequest(request_id, texts, config, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BatchClassifyRequest> = object :
        ProtoAdapter<BatchClassifyRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      BatchClassifyRequest::class, 
      "type.googleapis.com/com.augmentalis.rpc.nlu.BatchClassifyRequest", 
      PROTO_3, 
      null, 
      "nlu.proto"
    ) {
      override fun encodedSize(`value`: BatchClassifyRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.texts)
        if (value.config != null) {
          size += ClassifyConfig.ADAPTER.encodedSizeWithTag(3, value.config)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: BatchClassifyRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.texts)
        if (value.config != null) {
          ClassifyConfig.ADAPTER.encodeWithTag(writer, 3, value.config)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: BatchClassifyRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.config != null) {
          ClassifyConfig.ADAPTER.encodeWithTag(writer, 3, value.config)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.texts)
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): BatchClassifyRequest {
        var request_id: String = ""
        val texts = mutableListOf<String>()
        var config: ClassifyConfig? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> texts.add(ProtoAdapter.STRING.decode(reader))
            3 -> config = ClassifyConfig.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return BatchClassifyRequest(
          request_id = request_id,
          texts = texts,
          config = config,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: BatchClassifyRequest): BatchClassifyRequest = value.copy(
        config = value.config?.let(ClassifyConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
