// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.nlu.Entity in nlu.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.nlu

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

public class Entity(
  /**
   * Entity type
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val type: String = "",
  /**
   * Normalized value
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "value",
    schemaIndex = 1,
  )
  public val value_: String = "",
  /**
   * Original text
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "rawText",
    schemaIndex = 2,
  )
  public val raw_text: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val confidence: Float = 0f,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val start: Int = 0,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val end: Int = 0,
  metadata: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Entity, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 7,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 6,
  )
  public val metadata: Map<String, String> = immutableCopyOf("metadata", metadata)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Entity) return false
    if (unknownFields != other.unknownFields) return false
    if (type != other.type) return false
    if (value_ != other.value_) return false
    if (raw_text != other.raw_text) return false
    if (confidence != other.confidence) return false
    if (start != other.start) return false
    if (end != other.end) return false
    if (metadata != other.metadata) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + value_.hashCode()
      result = result * 37 + raw_text.hashCode()
      result = result * 37 + confidence.hashCode()
      result = result * 37 + start.hashCode()
      result = result * 37 + end.hashCode()
      result = result * 37 + metadata.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """type=${sanitize(type)}"""
    result += """value_=${sanitize(value_)}"""
    result += """raw_text=${sanitize(raw_text)}"""
    result += """confidence=$confidence"""
    result += """start=$start"""
    result += """end=$end"""
    if (metadata.isNotEmpty()) result += """metadata=$metadata"""
    return result.joinToString(prefix = "Entity{", separator = ", ", postfix = "}")
  }

  public fun copy(
    type: String = this.type,
    value_: String = this.value_,
    raw_text: String = this.raw_text,
    confidence: Float = this.confidence,
    start: Int = this.start,
    end: Int = this.end,
    metadata: Map<String, String> = this.metadata,
    unknownFields: ByteString = this.unknownFields,
  ): Entity = Entity(type, value_, raw_text, confidence, start, end, metadata, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Entity> = object : ProtoAdapter<Entity>(
      FieldEncoding.LENGTH_DELIMITED, 
      Entity::class, 
      "type.googleapis.com/com.augmentalis.rpc.nlu.Entity", 
      PROTO_3, 
      null, 
      "nlu.proto"
    ) {
      private val metadataAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: Entity): Int {
        var size = value.unknownFields.size
        if (value.type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.type)
        }
        if (value.value_ != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.value_)
        }
        if (value.raw_text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.raw_text)
        }
        if (!value.confidence.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(4, value.confidence)
        }
        if (value.start != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.start)
        }
        if (value.end != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(6, value.end)
        }
        size += metadataAdapter.encodedSizeWithTag(7, value.metadata)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Entity) {
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
        if (value.value_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value_)
        }
        if (value.raw_text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.raw_text)
        }
        if (!value.confidence.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.confidence)
        }
        if (value.start != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.start)
        }
        if (value.end != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 6, value.end)
        }
        metadataAdapter.encodeWithTag(writer, 7, value.metadata)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Entity) {
        writer.writeBytes(value.unknownFields)
        metadataAdapter.encodeWithTag(writer, 7, value.metadata)
        if (value.end != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 6, value.end)
        }
        if (value.start != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.start)
        }
        if (!value.confidence.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.confidence)
        }
        if (value.raw_text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.raw_text)
        }
        if (value.value_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value_)
        }
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
      }

      override fun decode(reader: ProtoReader): Entity {
        var type: String = ""
        var value_: String = ""
        var raw_text: String = ""
        var confidence: Float = 0f
        var start: Int = 0
        var end: Int = 0
        val metadata = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> type = ProtoAdapter.STRING.decode(reader)
            2 -> value_ = ProtoAdapter.STRING.decode(reader)
            3 -> raw_text = ProtoAdapter.STRING.decode(reader)
            4 -> confidence = ProtoAdapter.FLOAT.decode(reader)
            5 -> start = ProtoAdapter.INT32.decode(reader)
            6 -> end = ProtoAdapter.INT32.decode(reader)
            7 -> metadata.putAll(metadataAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return Entity(
          type = type,
          value_ = value_,
          raw_text = raw_text,
          confidence = confidence,
          start = start,
          end = end,
          metadata = metadata,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Entity): Entity = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
