// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.nlu.NLUService in nlu.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.nlu

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import kotlin.Suppress

/**
 * Service definition
 */
public class GrpcNLUServiceClient(
  private val client: GrpcClient,
) : NLUServiceClient {
  /**
   * Classify intent
   */
  override fun Classify(): GrpcCall<ClassifyRequest, ClassifyResponse> = client.newCall(GrpcMethod(
      path = "/com.augmentalis.rpc.nlu.NLUService/Classify",
      requestAdapter = ClassifyRequest.ADAPTER,
      responseAdapter = ClassifyResponse.ADAPTER
  ))

  /**
   * Extract entities
   */
  override fun ExtractEntities(): GrpcCall<ExtractEntitiesRequest, ExtractEntitiesResponse> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.rpc.nlu.NLUService/ExtractEntities",
      requestAdapter = ExtractEntitiesRequest.ADAPTER,
      responseAdapter = ExtractEntitiesResponse.ADAPTER
  ))

  /**
   * Parse voice command
   */
  override fun ParseCommand(): GrpcCall<ParseCommandRequest, ParsedCommand> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.rpc.nlu.NLUService/ParseCommand",
      requestAdapter = ParseCommandRequest.ADAPTER,
      responseAdapter = ParsedCommand.ADAPTER
  ))

  /**
   * Batch classify
   */
  override fun BatchClassify(): GrpcCall<BatchClassifyRequest, BatchClassifyResponse> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.rpc.nlu.NLUService/BatchClassify",
      requestAdapter = BatchClassifyRequest.ADAPTER,
      responseAdapter = BatchClassifyResponse.ADAPTER
  ))

  /**
   * Get available models
   */
  override fun GetModels(): GrpcCall<GetModelsRequest, ModelsResponse> = client.newCall(GrpcMethod(
      path = "/com.augmentalis.rpc.nlu.NLUService/GetModels",
      requestAdapter = GetModelsRequest.ADAPTER,
      responseAdapter = ModelsResponse.ADAPTER
  ))
}
