// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.nlu.Intent in nlu.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.nlu

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Intent classification result
 */
public class Intent(
  /**
   * Intent name
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val name: String = "",
  /**
   * Confidence score (0-1)
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val confidence: Float = 0f,
  slots: List<Slot> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Intent, Nothing>(ADAPTER, unknownFields) {
  /**
   * Extracted slots
   */
  @field:WireField(
    tag = 3,
    adapter = "com.augmentalis.rpc.nlu.Slot#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val slots: List<Slot> = immutableCopyOf("slots", slots)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Intent) return false
    if (unknownFields != other.unknownFields) return false
    if (name != other.name) return false
    if (confidence != other.confidence) return false
    if (slots != other.slots) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + confidence.hashCode()
      result = result * 37 + slots.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """name=${sanitize(name)}"""
    result += """confidence=$confidence"""
    if (slots.isNotEmpty()) result += """slots=$slots"""
    return result.joinToString(prefix = "Intent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    name: String = this.name,
    confidence: Float = this.confidence,
    slots: List<Slot> = this.slots,
    unknownFields: ByteString = this.unknownFields,
  ): Intent = Intent(name, confidence, slots, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Intent> = object : ProtoAdapter<Intent>(
      FieldEncoding.LENGTH_DELIMITED, 
      Intent::class, 
      "type.googleapis.com/com.augmentalis.rpc.nlu.Intent", 
      PROTO_3, 
      null, 
      "nlu.proto"
    ) {
      override fun encodedSize(`value`: Intent): Int {
        var size = value.unknownFields.size
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.name)
        }
        if (!value.confidence.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(2, value.confidence)
        }
        size += Slot.ADAPTER.asRepeated().encodedSizeWithTag(3, value.slots)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Intent) {
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        }
        if (!value.confidence.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.confidence)
        }
        Slot.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.slots)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Intent) {
        writer.writeBytes(value.unknownFields)
        Slot.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.slots)
        if (!value.confidence.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.confidence)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        }
      }

      override fun decode(reader: ProtoReader): Intent {
        var name: String = ""
        var confidence: Float = 0f
        val slots = mutableListOf<Slot>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            2 -> confidence = ProtoAdapter.FLOAT.decode(reader)
            3 -> slots.add(Slot.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return Intent(
          name = name,
          confidence = confidence,
          slots = slots,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Intent): Intent = value.copy(
        slots = value.slots.redactElements(Slot.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
