// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.nlu.ModelInfo in nlu.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.nlu

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class ModelInfo(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val name: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val version: String = "",
  supported_languages: List<String> = emptyList(),
  domains: List<String> = emptyList(),
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val loaded: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ModelInfo, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "supportedLanguages",
    schemaIndex = 2,
  )
  public val supported_languages: List<String> = immutableCopyOf("supported_languages",
      supported_languages)

  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 3,
  )
  public val domains: List<String> = immutableCopyOf("domains", domains)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ModelInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (name != other.name) return false
    if (version != other.version) return false
    if (supported_languages != other.supported_languages) return false
    if (domains != other.domains) return false
    if (loaded != other.loaded) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + version.hashCode()
      result = result * 37 + supported_languages.hashCode()
      result = result * 37 + domains.hashCode()
      result = result * 37 + loaded.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """name=${sanitize(name)}"""
    result += """version=${sanitize(version)}"""
    if (supported_languages.isNotEmpty()) result +=
        """supported_languages=${sanitize(supported_languages)}"""
    if (domains.isNotEmpty()) result += """domains=${sanitize(domains)}"""
    result += """loaded=$loaded"""
    return result.joinToString(prefix = "ModelInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    name: String = this.name,
    version: String = this.version,
    supported_languages: List<String> = this.supported_languages,
    domains: List<String> = this.domains,
    loaded: Boolean = this.loaded,
    unknownFields: ByteString = this.unknownFields,
  ): ModelInfo = ModelInfo(name, version, supported_languages, domains, loaded, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ModelInfo> = object : ProtoAdapter<ModelInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      ModelInfo::class, 
      "type.googleapis.com/com.augmentalis.rpc.nlu.ModelInfo", 
      PROTO_3, 
      null, 
      "nlu.proto"
    ) {
      override fun encodedSize(`value`: ModelInfo): Int {
        var size = value.unknownFields.size
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.name)
        }
        if (value.version != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.version)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.supported_languages)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(4, value.domains)
        if (value.loaded != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(5, value.loaded)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ModelInfo) {
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        }
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.version)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.supported_languages)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.domains)
        if (value.loaded != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.loaded)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ModelInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.loaded != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.loaded)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.domains)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.supported_languages)
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.version)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        }
      }

      override fun decode(reader: ProtoReader): ModelInfo {
        var name: String = ""
        var version: String = ""
        val supported_languages = mutableListOf<String>()
        val domains = mutableListOf<String>()
        var loaded: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            2 -> version = ProtoAdapter.STRING.decode(reader)
            3 -> supported_languages.add(ProtoAdapter.STRING.decode(reader))
            4 -> domains.add(ProtoAdapter.STRING.decode(reader))
            5 -> loaded = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ModelInfo(
          name = name,
          version = version,
          supported_languages = supported_languages,
          domains = domains,
          loaded = loaded,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ModelInfo): ModelInfo = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
