// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.ava.ProviderResponse in ava.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.ava

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ProviderResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val success: Boolean = false,
  @field:WireField(
    tag = 3,
    adapter = "com.augmentalis.universalrpc.ava.ProviderInfo#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val provider: ProviderInfo? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ProviderResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ProviderResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (success != other.success) return false
    if (provider != other.provider) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + success.hashCode()
      result = result * 37 + (provider?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """success=$success"""
    if (provider != null) result += """provider=$provider"""
    return result.joinToString(prefix = "ProviderResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    success: Boolean = this.success,
    provider: ProviderInfo? = this.provider,
    unknownFields: ByteString = this.unknownFields,
  ): ProviderResponse = ProviderResponse(request_id, success, provider, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ProviderResponse> = object : ProtoAdapter<ProviderResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ProviderResponse::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.ava.ProviderResponse", 
      PROTO_3, 
      null, 
      "ava.proto"
    ) {
      override fun encodedSize(`value`: ProviderResponse): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.success != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(2, value.success)
        }
        if (value.provider != null) {
          size += ProviderInfo.ADAPTER.encodedSizeWithTag(3, value.provider)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ProviderResponse) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.success != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.success)
        }
        if (value.provider != null) {
          ProviderInfo.ADAPTER.encodeWithTag(writer, 3, value.provider)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ProviderResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.provider != null) {
          ProviderInfo.ADAPTER.encodeWithTag(writer, 3, value.provider)
        }
        if (value.success != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.success)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): ProviderResponse {
        var request_id: String = ""
        var success: Boolean = false
        var provider: ProviderInfo? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> success = ProtoAdapter.BOOL.decode(reader)
            3 -> provider = ProviderInfo.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ProviderResponse(
          request_id = request_id,
          success = success,
          provider = provider,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ProviderResponse): ProviderResponse = value.copy(
        provider = value.provider?.let(ProviderInfo.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
