// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.plugin.HealthCheckResponse in plugin.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.plugin

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * Health check response
 */
public class HealthCheckResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val healthy: Boolean = false,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "statusMessage",
    schemaIndex = 2,
  )
  public val status_message: String = "",
  diagnostics: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<HealthCheckResponse, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 4,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 3,
  )
  public val diagnostics: Map<String, String> = immutableCopyOf("diagnostics", diagnostics)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is HealthCheckResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (healthy != other.healthy) return false
    if (status_message != other.status_message) return false
    if (diagnostics != other.diagnostics) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + healthy.hashCode()
      result = result * 37 + status_message.hashCode()
      result = result * 37 + diagnostics.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """healthy=$healthy"""
    result += """status_message=${sanitize(status_message)}"""
    if (diagnostics.isNotEmpty()) result += """diagnostics=$diagnostics"""
    return result.joinToString(prefix = "HealthCheckResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    healthy: Boolean = this.healthy,
    status_message: String = this.status_message,
    diagnostics: Map<String, String> = this.diagnostics,
    unknownFields: ByteString = this.unknownFields,
  ): HealthCheckResponse = HealthCheckResponse(request_id, healthy, status_message, diagnostics, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<HealthCheckResponse> = object : ProtoAdapter<HealthCheckResponse>(
      FieldEncoding.LENGTH_DELIMITED,
      HealthCheckResponse::class,
      "type.googleapis.com/com.augmentalis.rpc.plugin.HealthCheckResponse",
      PROTO_3,
      null,
      "plugin.proto"
    ) {
      private val diagnosticsAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: HealthCheckResponse): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.healthy != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(2, value.healthy)
        }
        if (value.status_message != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.status_message)
        }
        size += diagnosticsAdapter.encodedSizeWithTag(4, value.diagnostics)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: HealthCheckResponse) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.healthy != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.healthy)
        }
        if (value.status_message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.status_message)
        }
        diagnosticsAdapter.encodeWithTag(writer, 4, value.diagnostics)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: HealthCheckResponse) {
        writer.writeBytes(value.unknownFields)
        diagnosticsAdapter.encodeWithTag(writer, 4, value.diagnostics)
        if (value.status_message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.status_message)
        }
        if (value.healthy != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.healthy)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): HealthCheckResponse {
        var request_id: String = ""
        var healthy: Boolean = false
        var status_message: String = ""
        val diagnostics = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> healthy = ProtoAdapter.BOOL.decode(reader)
            3 -> status_message = ProtoAdapter.STRING.decode(reader)
            4 -> diagnostics.putAll(diagnosticsAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return HealthCheckResponse(
          request_id = request_id,
          healthy = healthy,
          status_message = status_message,
          diagnostics = diagnostics,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: HealthCheckResponse): HealthCheckResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
