// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.plugin.DiscoverPluginsRequest in plugin.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.plugin

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Plugin discovery request
 */
public class DiscoverPluginsRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  capability_filter: List<String> = emptyList(),
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "includeDisabled",
    schemaIndex = 2,
  )
  public val include_disabled: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DiscoverPluginsRequest, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "capabilityFilter",
    schemaIndex = 1,
  )
  public val capability_filter: List<String> = immutableCopyOf("capability_filter", capability_filter)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DiscoverPluginsRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (capability_filter != other.capability_filter) return false
    if (include_disabled != other.include_disabled) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + capability_filter.hashCode()
      result = result * 37 + include_disabled.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    if (capability_filter.isNotEmpty()) result += """capability_filter=$capability_filter"""
    result += """include_disabled=$include_disabled"""
    return result.joinToString(prefix = "DiscoverPluginsRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    capability_filter: List<String> = this.capability_filter,
    include_disabled: Boolean = this.include_disabled,
    unknownFields: ByteString = this.unknownFields,
  ): DiscoverPluginsRequest = DiscoverPluginsRequest(request_id, capability_filter, include_disabled, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DiscoverPluginsRequest> = object : ProtoAdapter<DiscoverPluginsRequest>(
      FieldEncoding.LENGTH_DELIMITED,
      DiscoverPluginsRequest::class,
      "type.googleapis.com/com.augmentalis.universalrpc.plugin.DiscoverPluginsRequest",
      PROTO_3,
      null,
      "plugin.proto"
    ) {
      override fun encodedSize(`value`: DiscoverPluginsRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.capability_filter)
        if (value.include_disabled != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.include_disabled)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DiscoverPluginsRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.capability_filter)
        if (value.include_disabled != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.include_disabled)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DiscoverPluginsRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.include_disabled != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.include_disabled)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.capability_filter)
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): DiscoverPluginsRequest {
        var request_id: String = ""
        val capability_filter = mutableListOf<String>()
        var include_disabled: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> capability_filter.add(ProtoAdapter.STRING.decode(reader))
            3 -> include_disabled = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DiscoverPluginsRequest(
          request_id = request_id,
          capability_filter = capability_filter,
          include_disabled = include_disabled,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DiscoverPluginsRequest): DiscoverPluginsRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
