// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.plugin.PluginService in plugin.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.plugin

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import com.squareup.wire.GrpcStreamingCall
import kotlin.Suppress

/**
 * Plugin Service Definition
 *
 * Universal Plugin Architecture - Phase 1 Foundation
 * Provides plugin registration, discovery, lifecycle, and event bus
 */
public class GrpcPluginServiceClient(
  private val client: GrpcClient,
) : PluginServiceClient {
  /**
   * Register a plugin with the system
   */
  override fun RegisterPlugin(): GrpcCall<RegisterPluginRequest, RegisterPluginResponse> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.plugin.PluginService/RegisterPlugin",
      requestAdapter = RegisterPluginRequest.ADAPTER,
      responseAdapter = RegisterPluginResponse.ADAPTER
  ))

  /**
   * Unregister a plugin from the system
   */
  override fun UnregisterPlugin(): GrpcCall<UnregisterPluginRequest, UnregisterPluginResponse> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.plugin.PluginService/UnregisterPlugin",
      requestAdapter = UnregisterPluginRequest.ADAPTER,
      responseAdapter = UnregisterPluginResponse.ADAPTER
  ))

  /**
   * Discover available plugins, optionally filtered by capabilities
   */
  override fun DiscoverPlugins(): GrpcCall<DiscoverPluginsRequest, DiscoverPluginsResponse> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.plugin.PluginService/DiscoverPlugins",
      requestAdapter = DiscoverPluginsRequest.ADAPTER,
      responseAdapter = DiscoverPluginsResponse.ADAPTER
  ))

  /**
   * Get detailed information about a specific plugin
   */
  override fun GetPluginInfo(): GrpcCall<GetPluginInfoRequest, PluginInfo> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.plugin.PluginService/GetPluginInfo",
      requestAdapter = GetPluginInfoRequest.ADAPTER,
      responseAdapter = PluginInfo.ADAPTER
  ))

  /**
   * Send a lifecycle command to a plugin (activate, pause, resume, stop, config changed)
   */
  override fun SendLifecycleCommand(): GrpcCall<LifecycleCommand, LifecycleResponse> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.plugin.PluginService/SendLifecycleCommand",
      requestAdapter = LifecycleCommand.ADAPTER,
      responseAdapter = LifecycleResponse.ADAPTER
  ))

  /**
   * Subscribe to plugin events (server streaming)
   * Returns a stream of PluginEvent messages based on subscription filters
   */
  override fun SubscribeEvents(): GrpcStreamingCall<SubscribeEventsRequest, PluginEvent> =
      client.newStreamingCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.plugin.PluginService/SubscribeEvents",
      requestAdapter = SubscribeEventsRequest.ADAPTER,
      responseAdapter = PluginEvent.ADAPTER
  ))

  /**
   * Publish an event to the plugin event bus
   */
  override fun PublishEvent(): GrpcCall<PluginEvent, PublishEventResponse> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.plugin.PluginService/PublishEvent",
      requestAdapter = PluginEvent.ADAPTER,
      responseAdapter = PublishEventResponse.ADAPTER
  ))

  /**
   * Check health status of a specific plugin
   */
  override fun HealthCheck(): GrpcCall<HealthCheckRequest, HealthCheckResponse> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.plugin.PluginService/HealthCheck",
      requestAdapter = HealthCheckRequest.ADAPTER,
      responseAdapter = HealthCheckResponse.ADAPTER
  ))
}
