// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.plugin.HealthCheckRequest in plugin.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.plugin

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Health check request
 */
public class HealthCheckRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "pluginId",
    schemaIndex = 1,
  )
  public val plugin_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<HealthCheckRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is HealthCheckRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (plugin_id != other.plugin_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + plugin_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """plugin_id=${sanitize(plugin_id)}"""
    return result.joinToString(prefix = "HealthCheckRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    plugin_id: String = this.plugin_id,
    unknownFields: ByteString = this.unknownFields,
  ): HealthCheckRequest = HealthCheckRequest(request_id, plugin_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<HealthCheckRequest> = object : ProtoAdapter<HealthCheckRequest>(
      FieldEncoding.LENGTH_DELIMITED,
      HealthCheckRequest::class,
      "type.googleapis.com/com.augmentalis.universalrpc.plugin.HealthCheckRequest",
      PROTO_3,
      null,
      "plugin.proto"
    ) {
      override fun encodedSize(`value`: HealthCheckRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.plugin_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.plugin_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: HealthCheckRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.plugin_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.plugin_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: HealthCheckRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.plugin_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.plugin_id)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): HealthCheckRequest {
        var request_id: String = ""
        var plugin_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> plugin_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return HealthCheckRequest(
          request_id = request_id,
          plugin_id = plugin_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: HealthCheckRequest): HealthCheckRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
