// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.plugin.LifecycleResponse in plugin.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.plugin

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Lifecycle command response
 */
public class LifecycleResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val success: Boolean = false,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val message: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.augmentalis.universalrpc.plugin.PluginStateProto#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "newState",
    schemaIndex = 3,
  )
  public val new_state: PluginStateProto = PluginStateProto.PLUGIN_STATE_UNKNOWN,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LifecycleResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LifecycleResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (success != other.success) return false
    if (message != other.message) return false
    if (new_state != other.new_state) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + success.hashCode()
      result = result * 37 + message.hashCode()
      result = result * 37 + new_state.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """success=$success"""
    result += """message=${sanitize(message)}"""
    result += """new_state=$new_state"""
    return result.joinToString(prefix = "LifecycleResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    success: Boolean = this.success,
    message: String = this.message,
    new_state: PluginStateProto = this.new_state,
    unknownFields: ByteString = this.unknownFields,
  ): LifecycleResponse = LifecycleResponse(request_id, success, message, new_state, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LifecycleResponse> = object : ProtoAdapter<LifecycleResponse>(
      FieldEncoding.LENGTH_DELIMITED,
      LifecycleResponse::class,
      "type.googleapis.com/com.augmentalis.universalrpc.plugin.LifecycleResponse",
      PROTO_3,
      null,
      "plugin.proto"
    ) {
      override fun encodedSize(`value`: LifecycleResponse): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.success != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(2, value.success)
        }
        if (value.message != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.message)
        }
        if (value.new_state != PluginStateProto.PLUGIN_STATE_UNKNOWN) {
          size += PluginStateProto.ADAPTER.encodedSizeWithTag(4, value.new_state)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LifecycleResponse) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.success != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.success)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.message)
        }
        if (value.new_state != PluginStateProto.PLUGIN_STATE_UNKNOWN) {
          PluginStateProto.ADAPTER.encodeWithTag(writer, 4, value.new_state)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LifecycleResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.new_state != PluginStateProto.PLUGIN_STATE_UNKNOWN) {
          PluginStateProto.ADAPTER.encodeWithTag(writer, 4, value.new_state)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.message)
        }
        if (value.success != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.success)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): LifecycleResponse {
        var request_id: String = ""
        var success: Boolean = false
        var message: String = ""
        var new_state: PluginStateProto = PluginStateProto.PLUGIN_STATE_UNKNOWN
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> success = ProtoAdapter.BOOL.decode(reader)
            3 -> message = ProtoAdapter.STRING.decode(reader)
            4 -> try {
              new_state = PluginStateProto.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return LifecycleResponse(
          request_id = request_id,
          success = success,
          message = message,
          new_state = new_state,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LifecycleResponse): LifecycleResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
