// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.plugin.RegisterPluginRequest in plugin.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.plugin

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Plugin registration request
 */
public class RegisterPluginRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "pluginId",
    schemaIndex = 1,
  )
  public val plugin_id: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "pluginName",
    schemaIndex = 2,
  )
  public val plugin_name: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val version: String = "",
  capabilities: List<PluginCapabilityProto> = emptyList(),
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "endpointAddress",
    schemaIndex = 5,
  )
  public val endpoint_address: String = "",
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "endpointProtocol",
    schemaIndex = 6,
  )
  public val endpoint_protocol: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RegisterPluginRequest, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 5,
    adapter = "com.augmentalis.universalrpc.plugin.PluginCapabilityProto#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 4,
  )
  public val capabilities: List<PluginCapabilityProto> = immutableCopyOf("capabilities", capabilities)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RegisterPluginRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (plugin_id != other.plugin_id) return false
    if (plugin_name != other.plugin_name) return false
    if (version != other.version) return false
    if (capabilities != other.capabilities) return false
    if (endpoint_address != other.endpoint_address) return false
    if (endpoint_protocol != other.endpoint_protocol) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + plugin_id.hashCode()
      result = result * 37 + plugin_name.hashCode()
      result = result * 37 + version.hashCode()
      result = result * 37 + capabilities.hashCode()
      result = result * 37 + endpoint_address.hashCode()
      result = result * 37 + endpoint_protocol.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """plugin_id=${sanitize(plugin_id)}"""
    result += """plugin_name=${sanitize(plugin_name)}"""
    result += """version=${sanitize(version)}"""
    if (capabilities.isNotEmpty()) result += """capabilities=$capabilities"""
    result += """endpoint_address=${sanitize(endpoint_address)}"""
    result += """endpoint_protocol=${sanitize(endpoint_protocol)}"""
    return result.joinToString(prefix = "RegisterPluginRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    plugin_id: String = this.plugin_id,
    plugin_name: String = this.plugin_name,
    version: String = this.version,
    capabilities: List<PluginCapabilityProto> = this.capabilities,
    endpoint_address: String = this.endpoint_address,
    endpoint_protocol: String = this.endpoint_protocol,
    unknownFields: ByteString = this.unknownFields,
  ): RegisterPluginRequest = RegisterPluginRequest(request_id, plugin_id, plugin_name, version, capabilities, endpoint_address, endpoint_protocol, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RegisterPluginRequest> = object : ProtoAdapter<RegisterPluginRequest>(
      FieldEncoding.LENGTH_DELIMITED,
      RegisterPluginRequest::class,
      "type.googleapis.com/com.augmentalis.universalrpc.plugin.RegisterPluginRequest",
      PROTO_3,
      null,
      "plugin.proto"
    ) {
      override fun encodedSize(`value`: RegisterPluginRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.plugin_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.plugin_id)
        }
        if (value.plugin_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.plugin_name)
        }
        if (value.version != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.version)
        }
        size += PluginCapabilityProto.ADAPTER.asRepeated().encodedSizeWithTag(5, value.capabilities)
        if (value.endpoint_address != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.endpoint_address)
        }
        if (value.endpoint_protocol != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.endpoint_protocol)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RegisterPluginRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.plugin_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.plugin_id)
        }
        if (value.plugin_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.plugin_name)
        }
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.version)
        }
        PluginCapabilityProto.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.capabilities)
        if (value.endpoint_address != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.endpoint_address)
        }
        if (value.endpoint_protocol != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.endpoint_protocol)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RegisterPluginRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.endpoint_protocol != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.endpoint_protocol)
        }
        if (value.endpoint_address != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.endpoint_address)
        }
        PluginCapabilityProto.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.capabilities)
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.version)
        }
        if (value.plugin_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.plugin_name)
        }
        if (value.plugin_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.plugin_id)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): RegisterPluginRequest {
        var request_id: String = ""
        var plugin_id: String = ""
        var plugin_name: String = ""
        var version: String = ""
        val capabilities = mutableListOf<PluginCapabilityProto>()
        var endpoint_address: String = ""
        var endpoint_protocol: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> plugin_id = ProtoAdapter.STRING.decode(reader)
            3 -> plugin_name = ProtoAdapter.STRING.decode(reader)
            4 -> version = ProtoAdapter.STRING.decode(reader)
            5 -> capabilities.add(PluginCapabilityProto.ADAPTER.decode(reader))
            6 -> endpoint_address = ProtoAdapter.STRING.decode(reader)
            7 -> endpoint_protocol = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RegisterPluginRequest(
          request_id = request_id,
          plugin_id = plugin_id,
          plugin_name = plugin_name,
          version = version,
          capabilities = capabilities,
          endpoint_address = endpoint_address,
          endpoint_protocol = endpoint_protocol,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RegisterPluginRequest): RegisterPluginRequest = value.copy(
        capabilities = value.capabilities.redactElements(PluginCapabilityProto.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
