// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.plugin.SubscribeEventsRequest in plugin.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.plugin

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Subscribe to plugin events request
 */
public class SubscribeEventsRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "subscriberPluginId",
    schemaIndex = 1,
  )
  public val subscriber_plugin_id: String = "",
  event_types: List<String> = emptyList(),
  source_plugins: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SubscribeEventsRequest, Nothing>(ADAPTER, unknownFields) {
  /**
   * Filter by event type
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "eventTypes",
    schemaIndex = 2,
  )
  public val event_types: List<String> = immutableCopyOf("event_types", event_types)

  /**
   * Filter by source plugin
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "sourcePlugins",
    schemaIndex = 3,
  )
  public val source_plugins: List<String> = immutableCopyOf("source_plugins", source_plugins)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SubscribeEventsRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (subscriber_plugin_id != other.subscriber_plugin_id) return false
    if (event_types != other.event_types) return false
    if (source_plugins != other.source_plugins) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + subscriber_plugin_id.hashCode()
      result = result * 37 + event_types.hashCode()
      result = result * 37 + source_plugins.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """subscriber_plugin_id=${sanitize(subscriber_plugin_id)}"""
    if (event_types.isNotEmpty()) result += """event_types=$event_types"""
    if (source_plugins.isNotEmpty()) result += """source_plugins=$source_plugins"""
    return result.joinToString(prefix = "SubscribeEventsRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    subscriber_plugin_id: String = this.subscriber_plugin_id,
    event_types: List<String> = this.event_types,
    source_plugins: List<String> = this.source_plugins,
    unknownFields: ByteString = this.unknownFields,
  ): SubscribeEventsRequest = SubscribeEventsRequest(request_id, subscriber_plugin_id, event_types, source_plugins, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SubscribeEventsRequest> = object : ProtoAdapter<SubscribeEventsRequest>(
      FieldEncoding.LENGTH_DELIMITED,
      SubscribeEventsRequest::class,
      "type.googleapis.com/com.augmentalis.universalrpc.plugin.SubscribeEventsRequest",
      PROTO_3,
      null,
      "plugin.proto"
    ) {
      override fun encodedSize(`value`: SubscribeEventsRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.subscriber_plugin_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.subscriber_plugin_id)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.event_types)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(4, value.source_plugins)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SubscribeEventsRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.subscriber_plugin_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.subscriber_plugin_id)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.event_types)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.source_plugins)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SubscribeEventsRequest) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.source_plugins)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.event_types)
        if (value.subscriber_plugin_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.subscriber_plugin_id)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): SubscribeEventsRequest {
        var request_id: String = ""
        var subscriber_plugin_id: String = ""
        val event_types = mutableListOf<String>()
        val source_plugins = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> subscriber_plugin_id = ProtoAdapter.STRING.decode(reader)
            3 -> event_types.add(ProtoAdapter.STRING.decode(reader))
            4 -> source_plugins.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return SubscribeEventsRequest(
          request_id = request_id,
          subscriber_plugin_id = subscriber_plugin_id,
          event_types = event_types,
          source_plugins = source_plugins,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SubscribeEventsRequest): SubscribeEventsRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
