package com.augmentalis.nlu.usecase

import com.augmentalis.ava.core.common.Result
import com.augmentalis.ava.core.domain.model.TrainExample
import com.augmentalis.ava.core.domain.model.TrainExampleSource
import com.augmentalis.ava.core.domain.repository.TrainExampleRepository
import java.security.MessageDigest

/**
 * Use case: Train AVA with new intent example (Teach-Ava)
 *
 * Flow:
 * 1. Generate hash for deduplication
 * 2. Check for duplicates
 * 3. Add training example to repository
 * 4. Return success/duplicate error
 */
class TrainIntentUseCase(
    private val trainExampleRepository: TrainExampleRepository
) {

    /**
     * Add new training example
     *
     * @param utterance User example utterance
     * @param intent Intent to associate
     * @param locale Locale (default "en-US")
     * @param source Source of example (MANUAL, AUTO_LEARN, CORRECTION)
     * @return Result with created example or duplicate error
     */
    suspend operator fun invoke(
        utterance: String,
        intent: String,
        locale: String = "en-US",
        source: TrainExampleSource = TrainExampleSource.MANUAL
    ): Result<TrainExample> {
        try {
            // Validate inputs
            if (utterance.isBlank()) {
                return Result.Error(
                    exception = IllegalArgumentException("Empty utterance"),
                    message = "Utterance cannot be empty"
                )
            }

            if (intent.isBlank()) {
                return Result.Error(
                    exception = IllegalArgumentException("Empty intent"),
                    message = "Intent cannot be empty"
                )
            }

            // Generate hash for deduplication (VOS4 pattern)
            val exampleHash = generateHash(utterance, intent)

            // Check for duplicates
            val duplicateCheck = trainExampleRepository.findDuplicate(exampleHash)
            when (duplicateCheck) {
                is Result.Success -> {
                    if (duplicateCheck.data != null) {
                        return Result.Error(
                            exception = IllegalStateException("Duplicate example"),
                            message = "This training example already exists"
                        )
                    }
                }
                is Result.Error -> {
                    return Result.Error(
                        exception = duplicateCheck.exception,
                        message = "Failed to check for duplicates"
                    )
                }
            }

            // Create training example
            val example = TrainExample(
                id = 0, // Will be generated by repository
                exampleHash = exampleHash,
                utterance = utterance,
                intent = intent,
                locale = locale,
                source = source,
                createdAt = System.currentTimeMillis(),
                usageCount = 0,
                lastUsed = null
            )

            // Add to repository
            return trainExampleRepository.addTrainExample(example)
        } catch (e: Exception) {
            return Result.Error(
                exception = e,
                message = "Failed to add training example: ${e.message}"
            )
        }
    }

    /**
     * Generate MD5 hash for deduplication
     * VOS4 Pattern: Hash-based uniqueness
     */
    private fun generateHash(utterance: String, intent: String): String {
        val input = "$utterance$intent"
        val md = MessageDigest.getInstance("MD5")
        val digest = md.digest(input.toByteArray())
        return digest.joinToString("") { "%02x".format(it) }
    }
}
