// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.cockpit.DeviceEvent in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class DeviceEvent(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "deviceId",
    schemaIndex = 0,
  )
  public val device_id: String = "",
  /**
   * "connected", "disconnected", "status_change"
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "eventType",
    schemaIndex = 1,
  )
  public val event_type: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.augmentalis.rpc.cockpit.DeviceInfo#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val device: DeviceInfo? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val timestamp: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DeviceEvent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DeviceEvent) return false
    if (unknownFields != other.unknownFields) return false
    if (device_id != other.device_id) return false
    if (event_type != other.event_type) return false
    if (device != other.device) return false
    if (timestamp != other.timestamp) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + device_id.hashCode()
      result = result * 37 + event_type.hashCode()
      result = result * 37 + (device?.hashCode() ?: 0)
      result = result * 37 + timestamp.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """device_id=${sanitize(device_id)}"""
    result += """event_type=${sanitize(event_type)}"""
    if (device != null) result += """device=$device"""
    result += """timestamp=$timestamp"""
    return result.joinToString(prefix = "DeviceEvent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    device_id: String = this.device_id,
    event_type: String = this.event_type,
    device: DeviceInfo? = this.device,
    timestamp: Long = this.timestamp,
    unknownFields: ByteString = this.unknownFields,
  ): DeviceEvent = DeviceEvent(device_id, event_type, device, timestamp, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DeviceEvent> = object : ProtoAdapter<DeviceEvent>(
      FieldEncoding.LENGTH_DELIMITED, 
      DeviceEvent::class, 
      "type.googleapis.com/com.augmentalis.rpc.cockpit.DeviceEvent", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: DeviceEvent): Int {
        var size = value.unknownFields.size
        if (value.device_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.device_id)
        }
        if (value.event_type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.event_type)
        }
        if (value.device != null) {
          size += DeviceInfo.ADAPTER.encodedSizeWithTag(3, value.device)
        }
        if (value.timestamp != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(4, value.timestamp)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DeviceEvent) {
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.device_id)
        }
        if (value.event_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.event_type)
        }
        if (value.device != null) {
          DeviceInfo.ADAPTER.encodeWithTag(writer, 3, value.device)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.timestamp)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DeviceEvent) {
        writer.writeBytes(value.unknownFields)
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.timestamp)
        }
        if (value.device != null) {
          DeviceInfo.ADAPTER.encodeWithTag(writer, 3, value.device)
        }
        if (value.event_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.event_type)
        }
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.device_id)
        }
      }

      override fun decode(reader: ProtoReader): DeviceEvent {
        var device_id: String = ""
        var event_type: String = ""
        var device: DeviceInfo? = null
        var timestamp: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> device_id = ProtoAdapter.STRING.decode(reader)
            2 -> event_type = ProtoAdapter.STRING.decode(reader)
            3 -> device = DeviceInfo.ADAPTER.decode(reader)
            4 -> timestamp = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DeviceEvent(
          device_id = device_id,
          event_type = event_type,
          device = device,
          timestamp = timestamp,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DeviceEvent): DeviceEvent = value.copy(
        device = value.device?.let(DeviceInfo.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
