// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.cockpit.GetDevicesRequest in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class GetDevicesRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "onlineOnly",
    schemaIndex = 1,
  )
  public val online_only: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetDevicesRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetDevicesRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (online_only != other.online_only) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + online_only.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """online_only=$online_only"""
    return result.joinToString(prefix = "GetDevicesRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    online_only: Boolean = this.online_only,
    unknownFields: ByteString = this.unknownFields,
  ): GetDevicesRequest = GetDevicesRequest(request_id, online_only, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetDevicesRequest> = object : ProtoAdapter<GetDevicesRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetDevicesRequest::class, 
      "type.googleapis.com/com.augmentalis.rpc.cockpit.GetDevicesRequest", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: GetDevicesRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.online_only != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(2, value.online_only)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetDevicesRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.online_only != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.online_only)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetDevicesRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.online_only != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.online_only)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): GetDevicesRequest {
        var request_id: String = ""
        var online_only: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> online_only = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetDevicesRequest(
          request_id = request_id,
          online_only = online_only,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetDevicesRequest): GetDevicesRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
