// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.cockpit.StreamDeviceEventsRequest in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class StreamDeviceEventsRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  device_ids: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StreamDeviceEventsRequest, Nothing>(ADAPTER, unknownFields) {
  /**
   * Filter by devices
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "deviceIds",
    schemaIndex = 1,
  )
  public val device_ids: List<String> = immutableCopyOf("device_ids", device_ids)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StreamDeviceEventsRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (device_ids != other.device_ids) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + device_ids.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    if (device_ids.isNotEmpty()) result += """device_ids=${sanitize(device_ids)}"""
    return result.joinToString(prefix = "StreamDeviceEventsRequest{", separator = ", ", postfix =
        "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    device_ids: List<String> = this.device_ids,
    unknownFields: ByteString = this.unknownFields,
  ): StreamDeviceEventsRequest = StreamDeviceEventsRequest(request_id, device_ids, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StreamDeviceEventsRequest> = object :
        ProtoAdapter<StreamDeviceEventsRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      StreamDeviceEventsRequest::class, 
      "type.googleapis.com/com.augmentalis.rpc.cockpit.StreamDeviceEventsRequest", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: StreamDeviceEventsRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.device_ids)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: StreamDeviceEventsRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.device_ids)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: StreamDeviceEventsRequest) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.device_ids)
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): StreamDeviceEventsRequest {
        var request_id: String = ""
        val device_ids = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> device_ids.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return StreamDeviceEventsRequest(
          request_id = request_id,
          device_ids = device_ids,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: StreamDeviceEventsRequest): StreamDeviceEventsRequest =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
