// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.cockpit.SyncStatus in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Sync status
 */
public class SyncStatus(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  /**
   * "pending", "syncing", "completed", "failed"
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val state: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val progress: Float = 0f,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val message: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SyncStatus, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SyncStatus) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (state != other.state) return false
    if (progress != other.progress) return false
    if (message != other.message) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + state.hashCode()
      result = result * 37 + progress.hashCode()
      result = result * 37 + message.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """state=${sanitize(state)}"""
    result += """progress=$progress"""
    result += """message=${sanitize(message)}"""
    return result.joinToString(prefix = "SyncStatus{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    state: String = this.state,
    progress: Float = this.progress,
    message: String = this.message,
    unknownFields: ByteString = this.unknownFields,
  ): SyncStatus = SyncStatus(request_id, state, progress, message, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SyncStatus> = object : ProtoAdapter<SyncStatus>(
      FieldEncoding.LENGTH_DELIMITED, 
      SyncStatus::class, 
      "type.googleapis.com/com.augmentalis.rpc.cockpit.SyncStatus", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: SyncStatus): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.state != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.state)
        }
        if (!value.progress.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(3, value.progress)
        }
        if (value.message != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.message)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SyncStatus) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.state != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.state)
        }
        if (!value.progress.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.progress)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.message)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SyncStatus) {
        writer.writeBytes(value.unknownFields)
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.message)
        }
        if (!value.progress.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.progress)
        }
        if (value.state != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.state)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): SyncStatus {
        var request_id: String = ""
        var state: String = ""
        var progress: Float = 0f
        var message: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> state = ProtoAdapter.STRING.decode(reader)
            3 -> progress = ProtoAdapter.FLOAT.decode(reader)
            4 -> message = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SyncStatus(
          request_id = request_id,
          state = state,
          progress = progress,
          message = message,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SyncStatus): SyncStatus = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
