// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.ava.ChatResponse in ava.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.ava

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Chat response
 */
public class ChatResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.augmentalis.universalrpc.ava.ChatMessage#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val message: ChatMessage? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "isComplete",
    schemaIndex = 2,
  )
  public val is_complete: Boolean = false,
  @field:WireField(
    tag = 4,
    adapter = "com.augmentalis.universalrpc.ava.Usage#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val usage: Usage? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ChatResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (message != other.message) return false
    if (is_complete != other.is_complete) return false
    if (usage != other.usage) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + (message?.hashCode() ?: 0)
      result = result * 37 + is_complete.hashCode()
      result = result * 37 + (usage?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    if (message != null) result += """message=$message"""
    result += """is_complete=$is_complete"""
    if (usage != null) result += """usage=$usage"""
    return result.joinToString(prefix = "ChatResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    message: ChatMessage? = this.message,
    is_complete: Boolean = this.is_complete,
    usage: Usage? = this.usage,
    unknownFields: ByteString = this.unknownFields,
  ): ChatResponse = ChatResponse(request_id, message, is_complete, usage, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatResponse> = object : ProtoAdapter<ChatResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatResponse::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.ava.ChatResponse", 
      PROTO_3, 
      null, 
      "ava.proto"
    ) {
      override fun encodedSize(`value`: ChatResponse): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.message != null) {
          size += ChatMessage.ADAPTER.encodedSizeWithTag(2, value.message)
        }
        if (value.is_complete != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.is_complete)
        }
        if (value.usage != null) {
          size += Usage.ADAPTER.encodedSizeWithTag(4, value.usage)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatResponse) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.message != null) {
          ChatMessage.ADAPTER.encodeWithTag(writer, 2, value.message)
        }
        if (value.is_complete != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.is_complete)
        }
        if (value.usage != null) {
          Usage.ADAPTER.encodeWithTag(writer, 4, value.usage)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.usage != null) {
          Usage.ADAPTER.encodeWithTag(writer, 4, value.usage)
        }
        if (value.is_complete != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.is_complete)
        }
        if (value.message != null) {
          ChatMessage.ADAPTER.encodeWithTag(writer, 2, value.message)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): ChatResponse {
        var request_id: String = ""
        var message: ChatMessage? = null
        var is_complete: Boolean = false
        var usage: Usage? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> message = ChatMessage.ADAPTER.decode(reader)
            3 -> is_complete = ProtoAdapter.BOOL.decode(reader)
            4 -> usage = Usage.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatResponse(
          request_id = request_id,
          message = message,
          is_complete = is_complete,
          usage = usage,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatResponse): ChatResponse = value.copy(
        message = value.message?.let(ChatMessage.ADAPTER::redact),
        usage = value.usage?.let(Usage.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
