// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.ava.Usage in ava.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.ava

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class Usage(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "promptTokens",
    schemaIndex = 0,
  )
  public val prompt_tokens: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "completionTokens",
    schemaIndex = 1,
  )
  public val completion_tokens: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "totalTokens",
    schemaIndex = 2,
  )
  public val total_tokens: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Usage, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Usage) return false
    if (unknownFields != other.unknownFields) return false
    if (prompt_tokens != other.prompt_tokens) return false
    if (completion_tokens != other.completion_tokens) return false
    if (total_tokens != other.total_tokens) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + prompt_tokens.hashCode()
      result = result * 37 + completion_tokens.hashCode()
      result = result * 37 + total_tokens.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """prompt_tokens=$prompt_tokens"""
    result += """completion_tokens=$completion_tokens"""
    result += """total_tokens=$total_tokens"""
    return result.joinToString(prefix = "Usage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    prompt_tokens: Int = this.prompt_tokens,
    completion_tokens: Int = this.completion_tokens,
    total_tokens: Int = this.total_tokens,
    unknownFields: ByteString = this.unknownFields,
  ): Usage = Usage(prompt_tokens, completion_tokens, total_tokens, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Usage> = object : ProtoAdapter<Usage>(
      FieldEncoding.LENGTH_DELIMITED, 
      Usage::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.ava.Usage", 
      PROTO_3, 
      null, 
      "ava.proto"
    ) {
      override fun encodedSize(`value`: Usage): Int {
        var size = value.unknownFields.size
        if (value.prompt_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.prompt_tokens)
        }
        if (value.completion_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.completion_tokens)
        }
        if (value.total_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.total_tokens)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Usage) {
        if (value.prompt_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.prompt_tokens)
        }
        if (value.completion_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.completion_tokens)
        }
        if (value.total_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.total_tokens)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Usage) {
        writer.writeBytes(value.unknownFields)
        if (value.total_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.total_tokens)
        }
        if (value.completion_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.completion_tokens)
        }
        if (value.prompt_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.prompt_tokens)
        }
      }

      override fun decode(reader: ProtoReader): Usage {
        var prompt_tokens: Int = 0
        var completion_tokens: Int = 0
        var total_tokens: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> prompt_tokens = ProtoAdapter.INT32.decode(reader)
            2 -> completion_tokens = ProtoAdapter.INT32.decode(reader)
            3 -> total_tokens = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Usage(
          prompt_tokens = prompt_tokens,
          completion_tokens = completion_tokens,
          total_tokens = total_tokens,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Usage): Usage = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
