// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.exploration.ExplorationProgress in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.exploration

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Exploration progress
 */
public class ExplorationProgress(
  @field:WireField(
    tag = 1,
    adapter = "com.augmentalis.rpc.exploration.ExplorationState#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val state: ExplorationState = ExplorationState.EXPLORATION_IDLE,
  /**
   * 0-1 completion percentage
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val progress: Float = 0f,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "elementsFound",
    schemaIndex = 2,
  )
  public val elements_found: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "elementsLearned",
    schemaIndex = 3,
  )
  public val elements_learned: Int = 0,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "currentActivity",
    schemaIndex = 4,
  )
  public val current_activity: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val message: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ExplorationProgress, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ExplorationProgress) return false
    if (unknownFields != other.unknownFields) return false
    if (state != other.state) return false
    if (progress != other.progress) return false
    if (elements_found != other.elements_found) return false
    if (elements_learned != other.elements_learned) return false
    if (current_activity != other.current_activity) return false
    if (message != other.message) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + state.hashCode()
      result = result * 37 + progress.hashCode()
      result = result * 37 + elements_found.hashCode()
      result = result * 37 + elements_learned.hashCode()
      result = result * 37 + current_activity.hashCode()
      result = result * 37 + message.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """state=$state"""
    result += """progress=$progress"""
    result += """elements_found=$elements_found"""
    result += """elements_learned=$elements_learned"""
    result += """current_activity=${sanitize(current_activity)}"""
    result += """message=${sanitize(message)}"""
    return result.joinToString(prefix = "ExplorationProgress{", separator = ", ", postfix = "}")
  }

  public fun copy(
    state: ExplorationState = this.state,
    progress: Float = this.progress,
    elements_found: Int = this.elements_found,
    elements_learned: Int = this.elements_learned,
    current_activity: String = this.current_activity,
    message: String = this.message,
    unknownFields: ByteString = this.unknownFields,
  ): ExplorationProgress = ExplorationProgress(state, progress, elements_found, elements_learned,
      current_activity, message, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ExplorationProgress> = object :
        ProtoAdapter<ExplorationProgress>(
      FieldEncoding.LENGTH_DELIMITED, 
      ExplorationProgress::class, 
      "type.googleapis.com/com.augmentalis.rpc.exploration.ExplorationProgress", 
      PROTO_3, 
      null, 
      "exploration.proto"
    ) {
      override fun encodedSize(`value`: ExplorationProgress): Int {
        var size = value.unknownFields.size
        if (value.state !=
            com.augmentalis.rpc.exploration.ExplorationState.EXPLORATION_IDLE) {
          size += ExplorationState.ADAPTER.encodedSizeWithTag(1, value.state)
        }
        if (!value.progress.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(2, value.progress)
        }
        if (value.elements_found != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.elements_found)
        }
        if (value.elements_learned != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.elements_learned)
        }
        if (value.current_activity != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.current_activity)
        }
        if (value.message != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.message)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ExplorationProgress) {
        if (value.state !=
            com.augmentalis.rpc.exploration.ExplorationState.EXPLORATION_IDLE) {
          ExplorationState.ADAPTER.encodeWithTag(writer, 1, value.state)
        }
        if (!value.progress.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.progress)
        }
        if (value.elements_found != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.elements_found)
        }
        if (value.elements_learned != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.elements_learned)
        }
        if (value.current_activity != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.current_activity)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.message)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ExplorationProgress) {
        writer.writeBytes(value.unknownFields)
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.message)
        }
        if (value.current_activity != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.current_activity)
        }
        if (value.elements_learned != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.elements_learned)
        }
        if (value.elements_found != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.elements_found)
        }
        if (!value.progress.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.progress)
        }
        if (value.state !=
            com.augmentalis.rpc.exploration.ExplorationState.EXPLORATION_IDLE) {
          ExplorationState.ADAPTER.encodeWithTag(writer, 1, value.state)
        }
      }

      override fun decode(reader: ProtoReader): ExplorationProgress {
        var state: ExplorationState = ExplorationState.EXPLORATION_IDLE
        var progress: Float = 0f
        var elements_found: Int = 0
        var elements_learned: Int = 0
        var current_activity: String = ""
        var message: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              state = ExplorationState.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> progress = ProtoAdapter.FLOAT.decode(reader)
            3 -> elements_found = ProtoAdapter.INT32.decode(reader)
            4 -> elements_learned = ProtoAdapter.INT32.decode(reader)
            5 -> current_activity = ProtoAdapter.STRING.decode(reader)
            6 -> message = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ExplorationProgress(
          state = state,
          progress = progress,
          elements_found = elements_found,
          elements_learned = elements_learned,
          current_activity = current_activity,
          message = message,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ExplorationProgress): ExplorationProgress = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
