// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.exploration.ExplorationService in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.exploration

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcStreamingCall
import com.squareup.wire.Service
import kotlin.Suppress

/**
 * Service definition
 */
public interface ExplorationServiceClient : Service {
  /**
   * Start full exploration
   */
  public fun StartExploration(): GrpcCall<StartExplorationRequest, ExplorationResult>

  /**
   * Stop current exploration
   */
  public fun StopExploration(): GrpcCall<StopExplorationRequest, ExplorationResult>

  /**
   * Get exploration progress
   */
  public fun GetProgress(): GrpcCall<GetProgressRequest, ExplorationProgress>

  /**
   * JIT learning
   */
  public fun LearnJIT(): GrpcCall<JITLearnRequest, JITLearnResult>

  /**
   * Capture specific element
   */
  public fun CaptureElement(): GrpcCall<CaptureElementRequest, LearnedElement>

  /**
   * Stream exploration progress
   */
  public fun StreamProgress(): GrpcStreamingCall<StartExplorationRequest, ExplorationProgress>

  /**
   * Get learned data for app
   */
  public fun GetLearnedData(): GrpcCall<GetLearnedDataRequest, ExplorationResult>
}
