// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.exploration.JITLearnRequest in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.exploration

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * JIT learning request
 */
public class JITLearnRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "packageName",
    schemaIndex = 1,
  )
  public val package_name: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "activityName",
    schemaIndex = 2,
  )
  public val activity_name: String = "",
  /**
   * What user is trying to do
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "userIntent",
    schemaIndex = 3,
  )
  public val user_intent: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<JITLearnRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is JITLearnRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (package_name != other.package_name) return false
    if (activity_name != other.activity_name) return false
    if (user_intent != other.user_intent) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + package_name.hashCode()
      result = result * 37 + activity_name.hashCode()
      result = result * 37 + user_intent.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """package_name=${sanitize(package_name)}"""
    result += """activity_name=${sanitize(activity_name)}"""
    result += """user_intent=${sanitize(user_intent)}"""
    return result.joinToString(prefix = "JITLearnRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    package_name: String = this.package_name,
    activity_name: String = this.activity_name,
    user_intent: String = this.user_intent,
    unknownFields: ByteString = this.unknownFields,
  ): JITLearnRequest = JITLearnRequest(request_id, package_name, activity_name, user_intent,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<JITLearnRequest> = object : ProtoAdapter<JITLearnRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      JITLearnRequest::class, 
      "type.googleapis.com/com.augmentalis.rpc.exploration.JITLearnRequest", 
      PROTO_3, 
      null, 
      "exploration.proto"
    ) {
      override fun encodedSize(`value`: JITLearnRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.package_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.package_name)
        }
        if (value.activity_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.activity_name)
        }
        if (value.user_intent != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.user_intent)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: JITLearnRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        if (value.activity_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.activity_name)
        }
        if (value.user_intent != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.user_intent)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: JITLearnRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.user_intent != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.user_intent)
        }
        if (value.activity_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.activity_name)
        }
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): JITLearnRequest {
        var request_id: String = ""
        var package_name: String = ""
        var activity_name: String = ""
        var user_intent: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> package_name = ProtoAdapter.STRING.decode(reader)
            3 -> activity_name = ProtoAdapter.STRING.decode(reader)
            4 -> user_intent = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return JITLearnRequest(
          request_id = request_id,
          package_name = package_name,
          activity_name = activity_name,
          user_intent = user_intent,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: JITLearnRequest): JITLearnRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
