// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.exploration.LearnedScreen in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.exploration

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Learned screen data
 */
public class LearnedScreen(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "activityName",
    schemaIndex = 0,
  )
  public val activity_name: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "screenHash",
    schemaIndex = 1,
  )
  public val screen_hash: String = "",
  elements: List<LearnedElement> = emptyList(),
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "learnedAt",
    schemaIndex = 3,
  )
  public val learned_at: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LearnedScreen, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 3,
    adapter = "com.augmentalis.rpc.exploration.LearnedElement#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val elements: List<LearnedElement> = immutableCopyOf("elements", elements)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LearnedScreen) return false
    if (unknownFields != other.unknownFields) return false
    if (activity_name != other.activity_name) return false
    if (screen_hash != other.screen_hash) return false
    if (elements != other.elements) return false
    if (learned_at != other.learned_at) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + activity_name.hashCode()
      result = result * 37 + screen_hash.hashCode()
      result = result * 37 + elements.hashCode()
      result = result * 37 + learned_at.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """activity_name=${sanitize(activity_name)}"""
    result += """screen_hash=${sanitize(screen_hash)}"""
    if (elements.isNotEmpty()) result += """elements=$elements"""
    result += """learned_at=$learned_at"""
    return result.joinToString(prefix = "LearnedScreen{", separator = ", ", postfix = "}")
  }

  public fun copy(
    activity_name: String = this.activity_name,
    screen_hash: String = this.screen_hash,
    elements: List<LearnedElement> = this.elements,
    learned_at: Long = this.learned_at,
    unknownFields: ByteString = this.unknownFields,
  ): LearnedScreen = LearnedScreen(activity_name, screen_hash, elements, learned_at, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LearnedScreen> = object : ProtoAdapter<LearnedScreen>(
      FieldEncoding.LENGTH_DELIMITED, 
      LearnedScreen::class, 
      "type.googleapis.com/com.augmentalis.rpc.exploration.LearnedScreen", 
      PROTO_3, 
      null, 
      "exploration.proto"
    ) {
      override fun encodedSize(`value`: LearnedScreen): Int {
        var size = value.unknownFields.size
        if (value.activity_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.activity_name)
        }
        if (value.screen_hash != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.screen_hash)
        }
        size += LearnedElement.ADAPTER.asRepeated().encodedSizeWithTag(3, value.elements)
        if (value.learned_at != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(4, value.learned_at)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LearnedScreen) {
        if (value.activity_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.activity_name)
        }
        if (value.screen_hash != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.screen_hash)
        }
        LearnedElement.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.elements)
        if (value.learned_at != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.learned_at)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LearnedScreen) {
        writer.writeBytes(value.unknownFields)
        if (value.learned_at != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.learned_at)
        }
        LearnedElement.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.elements)
        if (value.screen_hash != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.screen_hash)
        }
        if (value.activity_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.activity_name)
        }
      }

      override fun decode(reader: ProtoReader): LearnedScreen {
        var activity_name: String = ""
        var screen_hash: String = ""
        val elements = mutableListOf<LearnedElement>()
        var learned_at: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> activity_name = ProtoAdapter.STRING.decode(reader)
            2 -> screen_hash = ProtoAdapter.STRING.decode(reader)
            3 -> elements.add(LearnedElement.ADAPTER.decode(reader))
            4 -> learned_at = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return LearnedScreen(
          activity_name = activity_name,
          screen_hash = screen_hash,
          elements = elements,
          learned_at = learned_at,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LearnedScreen): LearnedScreen = value.copy(
        elements = value.elements.redactElements(LearnedElement.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
