// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.exploration.LearnedElement in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.exploration

import com.augmentalis.rpc.avid.Bounds
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Learned element with generated commands
 */
public class LearnedElement(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val avid: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "elementType",
    schemaIndex = 1,
  )
  public val element_type: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val text: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "contentDesc",
    schemaIndex = 3,
  )
  public val content_desc: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.augmentalis.rpc.avid.Bounds#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val bounds: Bounds? = null,
  suggested_commands: List<String> = emptyList(),
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val confidence: Float = 0f,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LearnedElement, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "suggestedCommands",
    schemaIndex = 5,
  )
  public val suggested_commands: List<String> = immutableCopyOf("suggested_commands",
      suggested_commands)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LearnedElement) return false
    if (unknownFields != other.unknownFields) return false
    if (avid != other.avid) return false
    if (element_type != other.element_type) return false
    if (text != other.text) return false
    if (content_desc != other.content_desc) return false
    if (bounds != other.bounds) return false
    if (suggested_commands != other.suggested_commands) return false
    if (confidence != other.confidence) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + avid.hashCode()
      result = result * 37 + element_type.hashCode()
      result = result * 37 + text.hashCode()
      result = result * 37 + content_desc.hashCode()
      result = result * 37 + (bounds?.hashCode() ?: 0)
      result = result * 37 + suggested_commands.hashCode()
      result = result * 37 + confidence.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """avid=${sanitize(avid)}"""
    result += """element_type=${sanitize(element_type)}"""
    result += """text=${sanitize(text)}"""
    result += """content_desc=${sanitize(content_desc)}"""
    if (bounds != null) result += """bounds=$bounds"""
    if (suggested_commands.isNotEmpty()) result +=
        """suggested_commands=${sanitize(suggested_commands)}"""
    result += """confidence=$confidence"""
    return result.joinToString(prefix = "LearnedElement{", separator = ", ", postfix = "}")
  }

  public fun copy(
    avid: String = this.avid,
    element_type: String = this.element_type,
    text: String = this.text,
    content_desc: String = this.content_desc,
    bounds: Bounds? = this.bounds,
    suggested_commands: List<String> = this.suggested_commands,
    confidence: Float = this.confidence,
    unknownFields: ByteString = this.unknownFields,
  ): LearnedElement = LearnedElement(avid, element_type, text, content_desc, bounds,
      suggested_commands, confidence, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LearnedElement> = object : ProtoAdapter<LearnedElement>(
      FieldEncoding.LENGTH_DELIMITED, 
      LearnedElement::class, 
      "type.googleapis.com/com.augmentalis.rpc.exploration.LearnedElement", 
      PROTO_3, 
      null, 
      "exploration.proto"
    ) {
      override fun encodedSize(`value`: LearnedElement): Int {
        var size = value.unknownFields.size
        if (value.avid != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.avid)
        }
        if (value.element_type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.element_type)
        }
        if (value.text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.text)
        }
        if (value.content_desc != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.content_desc)
        }
        if (value.bounds != null) {
          size += Bounds.ADAPTER.encodedSizeWithTag(5, value.bounds)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(6, value.suggested_commands)
        if (!value.confidence.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(7, value.confidence)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LearnedElement) {
        if (value.avid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.avid)
        }
        if (value.element_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.element_type)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.text)
        }
        if (value.content_desc != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.content_desc)
        }
        if (value.bounds != null) {
          Bounds.ADAPTER.encodeWithTag(writer, 5, value.bounds)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 6, value.suggested_commands)
        if (!value.confidence.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 7, value.confidence)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LearnedElement) {
        writer.writeBytes(value.unknownFields)
        if (!value.confidence.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 7, value.confidence)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 6, value.suggested_commands)
        if (value.bounds != null) {
          Bounds.ADAPTER.encodeWithTag(writer, 5, value.bounds)
        }
        if (value.content_desc != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.content_desc)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.text)
        }
        if (value.element_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.element_type)
        }
        if (value.avid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.avid)
        }
      }

      override fun decode(reader: ProtoReader): LearnedElement {
        var avid: String = ""
        var element_type: String = ""
        var text: String = ""
        var content_desc: String = ""
        var bounds: Bounds? = null
        val suggested_commands = mutableListOf<String>()
        var confidence: Float = 0f
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> avid = ProtoAdapter.STRING.decode(reader)
            2 -> element_type = ProtoAdapter.STRING.decode(reader)
            3 -> text = ProtoAdapter.STRING.decode(reader)
            4 -> content_desc = ProtoAdapter.STRING.decode(reader)
            5 -> bounds = Bounds.ADAPTER.decode(reader)
            6 -> suggested_commands.add(ProtoAdapter.STRING.decode(reader))
            7 -> confidence = ProtoAdapter.FLOAT.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return LearnedElement(
          avid = avid,
          element_type = element_type,
          text = text,
          content_desc = content_desc,
          bounds = bounds,
          suggested_commands = suggested_commands,
          confidence = confidence,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LearnedElement): LearnedElement = value.copy(
        bounds = value.bounds?.let(Bounds.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
