// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.exploration.SuggestedAction in exploration.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.exploration

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class SuggestedAction(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val command: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val vuid: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "actionType",
    schemaIndex = 2,
  )
  public val action_type: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val confidence: Float = 0f,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val description: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SuggestedAction, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SuggestedAction) return false
    if (unknownFields != other.unknownFields) return false
    if (command != other.command) return false
    if (vuid != other.vuid) return false
    if (action_type != other.action_type) return false
    if (confidence != other.confidence) return false
    if (description != other.description) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + command.hashCode()
      result = result * 37 + vuid.hashCode()
      result = result * 37 + action_type.hashCode()
      result = result * 37 + confidence.hashCode()
      result = result * 37 + description.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """command=${sanitize(command)}"""
    result += """vuid=${sanitize(vuid)}"""
    result += """action_type=${sanitize(action_type)}"""
    result += """confidence=$confidence"""
    result += """description=${sanitize(description)}"""
    return result.joinToString(prefix = "SuggestedAction{", separator = ", ", postfix = "}")
  }

  public fun copy(
    command: String = this.command,
    vuid: String = this.vuid,
    action_type: String = this.action_type,
    confidence: Float = this.confidence,
    description: String = this.description,
    unknownFields: ByteString = this.unknownFields,
  ): SuggestedAction = SuggestedAction(command, vuid, action_type, confidence, description,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SuggestedAction> = object : ProtoAdapter<SuggestedAction>(
      FieldEncoding.LENGTH_DELIMITED, 
      SuggestedAction::class, 
      "type.googleapis.com/com.augmentalis.rpc.exploration.SuggestedAction", 
      PROTO_3, 
      null, 
      "exploration.proto"
    ) {
      override fun encodedSize(`value`: SuggestedAction): Int {
        var size = value.unknownFields.size
        if (value.command != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.command)
        }
        if (value.vuid != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.vuid)
        }
        if (value.action_type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.action_type)
        }
        if (!value.confidence.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(4, value.confidence)
        }
        if (value.description != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.description)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SuggestedAction) {
        if (value.command != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.command)
        }
        if (value.vuid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.vuid)
        }
        if (value.action_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.action_type)
        }
        if (!value.confidence.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.confidence)
        }
        if (value.description != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.description)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SuggestedAction) {
        writer.writeBytes(value.unknownFields)
        if (value.description != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.description)
        }
        if (!value.confidence.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.confidence)
        }
        if (value.action_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.action_type)
        }
        if (value.vuid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.vuid)
        }
        if (value.command != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.command)
        }
      }

      override fun decode(reader: ProtoReader): SuggestedAction {
        var command: String = ""
        var vuid: String = ""
        var action_type: String = ""
        var confidence: Float = 0f
        var description: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> command = ProtoAdapter.STRING.decode(reader)
            2 -> vuid = ProtoAdapter.STRING.decode(reader)
            3 -> action_type = ProtoAdapter.STRING.decode(reader)
            4 -> confidence = ProtoAdapter.FLOAT.decode(reader)
            5 -> description = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SuggestedAction(
          command = command,
          vuid = vuid,
          action_type = action_type,
          confidence = confidence,
          description = description,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SuggestedAction): SuggestedAction = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
