// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.avid.Bounds in avid.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.avid

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class Bounds(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val left: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val top: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val right: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val bottom: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Bounds, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Bounds) return false
    if (unknownFields != other.unknownFields) return false
    if (left != other.left) return false
    if (top != other.top) return false
    if (right != other.right) return false
    if (bottom != other.bottom) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + left.hashCode()
      result = result * 37 + top.hashCode()
      result = result * 37 + right.hashCode()
      result = result * 37 + bottom.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """left=$left"""
    result += """top=$top"""
    result += """right=$right"""
    result += """bottom=$bottom"""
    return result.joinToString(prefix = "Bounds{", separator = ", ", postfix = "}")
  }

  public fun copy(
    left: Int = this.left,
    top: Int = this.top,
    right: Int = this.right,
    bottom: Int = this.bottom,
    unknownFields: ByteString = this.unknownFields,
  ): Bounds = Bounds(left, top, right, bottom, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Bounds> = object : ProtoAdapter<Bounds>(
      FieldEncoding.LENGTH_DELIMITED,
      Bounds::class,
      "type.googleapis.com/com.augmentalis.rpc.avid.Bounds",
      PROTO_3,
      null,
      "avid.proto"
    ) {
      override fun encodedSize(`value`: Bounds): Int {
        var size = value.unknownFields.size
        if (value.left != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.left)
        }
        if (value.top != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.top)
        }
        if (value.right != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.right)
        }
        if (value.bottom != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.bottom)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Bounds) {
        if (value.left != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.left)
        }
        if (value.top != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.top)
        }
        if (value.right != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.right)
        }
        if (value.bottom != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.bottom)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Bounds) {
        writer.writeBytes(value.unknownFields)
        if (value.bottom != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.bottom)
        }
        if (value.right != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.right)
        }
        if (value.top != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.top)
        }
        if (value.left != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.left)
        }
      }

      override fun decode(reader: ProtoReader): Bounds {
        var left: Int = 0
        var top: Int = 0
        var right: Int = 0
        var bottom: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> left = ProtoAdapter.INT32.decode(reader)
            2 -> top = ProtoAdapter.INT32.decode(reader)
            3 -> right = ProtoAdapter.INT32.decode(reader)
            4 -> bottom = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Bounds(
          left = left,
          top = top,
          right = right,
          bottom = bottom,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Bounds): Bounds = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
