// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.avid.ElementQueryRequest in avid.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.avid

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Element query request
 */
public class ElementQueryRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "packageName",
    schemaIndex = 1,
  )
  public val package_name: String = "",
  /**
   * Query by AVID
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    oneofName = "query",
    schemaIndex = 2,
  )
  public val avid: String? = null,
  /**
   * Query by text
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    oneofName = "query",
    schemaIndex = 3,
  )
  public val text: String? = null,
  /**
   * Query by bounds
   */
  @field:WireField(
    tag = 5,
    adapter = "com.augmentalis.rpc.avid.Bounds#ADAPTER",
    oneofName = "query",
    schemaIndex = 4,
  )
  public val bounds: Bounds? = null,
  /**
   * Query by resource ID
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "resourceId",
    oneofName = "query",
    schemaIndex = 5,
  )
  public val resource_id: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ElementQueryRequest, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(avid, text, bounds, resource_id) <= 1) {
      "At most one of avid, text, bounds, resource_id may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ElementQueryRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (package_name != other.package_name) return false
    if (avid != other.avid) return false
    if (text != other.text) return false
    if (bounds != other.bounds) return false
    if (resource_id != other.resource_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + package_name.hashCode()
      result = result * 37 + (avid?.hashCode() ?: 0)
      result = result * 37 + (text?.hashCode() ?: 0)
      result = result * 37 + (bounds?.hashCode() ?: 0)
      result = result * 37 + (resource_id?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """package_name=${sanitize(package_name)}"""
    if (avid != null) result += """avid=${sanitize(avid)}"""
    if (text != null) result += """text=${sanitize(text)}"""
    if (bounds != null) result += """bounds=$bounds"""
    if (resource_id != null) result += """resource_id=${sanitize(resource_id)}"""
    return result.joinToString(prefix = "ElementQueryRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    package_name: String = this.package_name,
    avid: String? = this.avid,
    text: String? = this.text,
    bounds: Bounds? = this.bounds,
    resource_id: String? = this.resource_id,
    unknownFields: ByteString = this.unknownFields,
  ): ElementQueryRequest = ElementQueryRequest(request_id, package_name, avid, text, bounds,
      resource_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ElementQueryRequest> = object :
        ProtoAdapter<ElementQueryRequest>(
      FieldEncoding.LENGTH_DELIMITED,
      ElementQueryRequest::class,
      "type.googleapis.com/com.augmentalis.rpc.avid.ElementQueryRequest",
      PROTO_3,
      null,
      "avid.proto"
    ) {
      override fun encodedSize(`value`: ElementQueryRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.package_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.package_name)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.avid)
        size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.text)
        size += Bounds.ADAPTER.encodedSizeWithTag(5, value.bounds)
        size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.resource_id)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ElementQueryRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.avid)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.text)
        Bounds.ADAPTER.encodeWithTag(writer, 5, value.bounds)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.resource_id)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ElementQueryRequest) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.resource_id)
        Bounds.ADAPTER.encodeWithTag(writer, 5, value.bounds)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.text)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.avid)
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): ElementQueryRequest {
        var request_id: String = ""
        var package_name: String = ""
        var avid: String? = null
        var text: String? = null
        var bounds: Bounds? = null
        var resource_id: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> package_name = ProtoAdapter.STRING.decode(reader)
            3 -> avid = ProtoAdapter.STRING.decode(reader)
            4 -> text = ProtoAdapter.STRING.decode(reader)
            5 -> bounds = Bounds.ADAPTER.decode(reader)
            6 -> resource_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ElementQueryRequest(
          request_id = request_id,
          package_name = package_name,
          avid = avid,
          text = text,
          bounds = bounds,
          resource_id = resource_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ElementQueryRequest): ElementQueryRequest = value.copy(
        bounds = value.bounds?.let(Bounds.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
