// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.rpc.avid.StreamScreenRequest in avid.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.rpc.avid

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class StreamScreenRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "packageName",
    schemaIndex = 1,
  )
  public val package_name: String = "",
  /**
   * Debounce interval
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "debounceMs",
    schemaIndex = 2,
  )
  public val debounce_ms: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StreamScreenRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StreamScreenRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (package_name != other.package_name) return false
    if (debounce_ms != other.debounce_ms) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + package_name.hashCode()
      result = result * 37 + debounce_ms.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """package_name=${sanitize(package_name)}"""
    result += """debounce_ms=$debounce_ms"""
    return result.joinToString(prefix = "StreamScreenRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    package_name: String = this.package_name,
    debounce_ms: Int = this.debounce_ms,
    unknownFields: ByteString = this.unknownFields,
  ): StreamScreenRequest = StreamScreenRequest(request_id, package_name, debounce_ms, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StreamScreenRequest> = object :
        ProtoAdapter<StreamScreenRequest>(
      FieldEncoding.LENGTH_DELIMITED,
      StreamScreenRequest::class,
      "type.googleapis.com/com.augmentalis.rpc.avid.StreamScreenRequest",
      PROTO_3,
      null,
      "avid.proto"
    ) {
      override fun encodedSize(`value`: StreamScreenRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.package_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.package_name)
        }
        if (value.debounce_ms != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.debounce_ms)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: StreamScreenRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        if (value.debounce_ms != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.debounce_ms)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: StreamScreenRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.debounce_ms != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.debounce_ms)
        }
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): StreamScreenRequest {
        var request_id: String = ""
        var package_name: String = ""
        var debounce_ms: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> package_name = ProtoAdapter.STRING.decode(reader)
            3 -> debounce_ms = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return StreamScreenRequest(
          request_id = request_id,
          package_name = package_name,
          debounce_ms = debounce_ms,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: StreamScreenRequest): StreamScreenRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
