// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.voiceos.CommandRequest in voiceos.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.voiceos

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * Command execution request
 */
public class CommandRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "commandText",
    schemaIndex = 1,
  )
  public val command_text: String = "",
  context: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<CommandRequest, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 3,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val context: Map<String, String> = immutableCopyOf("context", context)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CommandRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (command_text != other.command_text) return false
    if (context != other.context) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + command_text.hashCode()
      result = result * 37 + context.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """command_text=${sanitize(command_text)}"""
    if (context.isNotEmpty()) result += """context=$context"""
    return result.joinToString(prefix = "CommandRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    command_text: String = this.command_text,
    context: Map<String, String> = this.context,
    unknownFields: ByteString = this.unknownFields,
  ): CommandRequest = CommandRequest(request_id, command_text, context, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CommandRequest> = object : ProtoAdapter<CommandRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      CommandRequest::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.voiceos.CommandRequest", 
      PROTO_3, 
      null, 
      "voiceos.proto"
    ) {
      private val contextAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: CommandRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.command_text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.command_text)
        }
        size += contextAdapter.encodedSizeWithTag(3, value.context)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: CommandRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.command_text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.command_text)
        }
        contextAdapter.encodeWithTag(writer, 3, value.context)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: CommandRequest) {
        writer.writeBytes(value.unknownFields)
        contextAdapter.encodeWithTag(writer, 3, value.context)
        if (value.command_text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.command_text)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): CommandRequest {
        var request_id: String = ""
        var command_text: String = ""
        val context = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> command_text = ProtoAdapter.STRING.decode(reader)
            3 -> context.putAll(contextAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return CommandRequest(
          request_id = request_id,
          command_text = command_text,
          context = context,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: CommandRequest): CommandRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
