// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.voiceos.GetCommandsRequest in voiceos.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.voiceos

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class GetCommandsRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "packageName",
    schemaIndex = 1,
  )
  public val package_name: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetCommandsRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetCommandsRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (package_name != other.package_name) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + package_name.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """package_name=${sanitize(package_name)}"""
    return result.joinToString(prefix = "GetCommandsRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    package_name: String = this.package_name,
    unknownFields: ByteString = this.unknownFields,
  ): GetCommandsRequest = GetCommandsRequest(request_id, package_name, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetCommandsRequest> = object :
        ProtoAdapter<GetCommandsRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetCommandsRequest::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.voiceos.GetCommandsRequest", 
      PROTO_3, 
      null, 
      "voiceos.proto"
    ) {
      override fun encodedSize(`value`: GetCommandsRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.package_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.package_name)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetCommandsRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetCommandsRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): GetCommandsRequest {
        var request_id: String = ""
        var package_name: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> package_name = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetCommandsRequest(
          request_id = request_id,
          package_name = package_name,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetCommandsRequest): GetCommandsRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
