// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.voiceos.StartVoiceRequest in voiceos.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.voiceos

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class StartVoiceRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val language: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "recognizerType",
    schemaIndex = 2,
  )
  public val recognizer_type: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StartVoiceRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StartVoiceRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (language != other.language) return false
    if (recognizer_type != other.recognizer_type) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + language.hashCode()
      result = result * 37 + recognizer_type.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """language=${sanitize(language)}"""
    result += """recognizer_type=${sanitize(recognizer_type)}"""
    return result.joinToString(prefix = "StartVoiceRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    language: String = this.language,
    recognizer_type: String = this.recognizer_type,
    unknownFields: ByteString = this.unknownFields,
  ): StartVoiceRequest = StartVoiceRequest(request_id, language, recognizer_type, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StartVoiceRequest> = object : ProtoAdapter<StartVoiceRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      StartVoiceRequest::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.voiceos.StartVoiceRequest", 
      PROTO_3, 
      null, 
      "voiceos.proto"
    ) {
      override fun encodedSize(`value`: StartVoiceRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.language != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.language)
        }
        if (value.recognizer_type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.recognizer_type)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: StartVoiceRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.language != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.language)
        }
        if (value.recognizer_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.recognizer_type)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: StartVoiceRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.recognizer_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.recognizer_type)
        }
        if (value.language != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.language)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): StartVoiceRequest {
        var request_id: String = ""
        var language: String = ""
        var recognizer_type: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> language = ProtoAdapter.STRING.decode(reader)
            3 -> recognizer_type = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return StartVoiceRequest(
          request_id = request_id,
          language = language,
          recognizer_type = recognizer_type,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: StartVoiceRequest): StartVoiceRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
