// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.voiceos.StreamEventsRequest in voiceos.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.voiceos

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class StreamEventsRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  event_types: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StreamEventsRequest, Nothing>(ADAPTER, unknownFields) {
  /**
   * Filter by event types
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "eventTypes",
    schemaIndex = 1,
  )
  public val event_types: List<String> = immutableCopyOf("event_types", event_types)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StreamEventsRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (event_types != other.event_types) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + event_types.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    if (event_types.isNotEmpty()) result += """event_types=${sanitize(event_types)}"""
    return result.joinToString(prefix = "StreamEventsRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    event_types: List<String> = this.event_types,
    unknownFields: ByteString = this.unknownFields,
  ): StreamEventsRequest = StreamEventsRequest(request_id, event_types, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StreamEventsRequest> = object :
        ProtoAdapter<StreamEventsRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      StreamEventsRequest::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.voiceos.StreamEventsRequest", 
      PROTO_3, 
      null, 
      "voiceos.proto"
    ) {
      override fun encodedSize(`value`: StreamEventsRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.event_types)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: StreamEventsRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.event_types)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: StreamEventsRequest) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.event_types)
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): StreamEventsRequest {
        var request_id: String = ""
        val event_types = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> event_types.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return StreamEventsRequest(
          request_id = request_id,
          event_types = event_types,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: StreamEventsRequest): StreamEventsRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
