// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.avid.AvidElement in avid.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.avid

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * AVID element data
 */
public class AvidElement(
  /**
   * Voice-addressable UID
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val avid: String = "",
  /**
   * App package name
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "packageName",
    schemaIndex = 1,
  )
  public val package_name: String = "",
  /**
   * Element class name
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "className",
    schemaIndex = 2,
  )
  public val class_name: String = "",
  /**
   * Element text content
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val text: String = "",
  /**
   * Content description
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "contentDesc",
    schemaIndex = 4,
  )
  public val content_desc: String = "",
  /**
   * Screen bounds
   */
  @field:WireField(
    tag = 6,
    adapter = "com.augmentalis.universalrpc.avid.Bounds#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val bounds: Bounds? = null,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val clickable: Boolean = false,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val scrollable: Boolean = false,
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 8,
  )
  public val focusable: Boolean = false,
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 9,
  )
  public val editable: Boolean = false,
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "resourceId",
    schemaIndex = 10,
  )
  public val resource_id: String = "",
  /**
   * Hierarchy depth
   */
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 11,
  )
  public val depth: Int = 0,
  children: List<AvidElement> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<AvidElement, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 13,
    adapter = "com.augmentalis.universalrpc.avid.AvidElement#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 12,
  )
  public val children: List<AvidElement> = immutableCopyOf("children", children)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AvidElement) return false
    if (unknownFields != other.unknownFields) return false
    if (avid != other.avid) return false
    if (package_name != other.package_name) return false
    if (class_name != other.class_name) return false
    if (text != other.text) return false
    if (content_desc != other.content_desc) return false
    if (bounds != other.bounds) return false
    if (clickable != other.clickable) return false
    if (scrollable != other.scrollable) return false
    if (focusable != other.focusable) return false
    if (editable != other.editable) return false
    if (resource_id != other.resource_id) return false
    if (depth != other.depth) return false
    if (children != other.children) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + avid.hashCode()
      result = result * 37 + package_name.hashCode()
      result = result * 37 + class_name.hashCode()
      result = result * 37 + text.hashCode()
      result = result * 37 + content_desc.hashCode()
      result = result * 37 + (bounds?.hashCode() ?: 0)
      result = result * 37 + clickable.hashCode()
      result = result * 37 + scrollable.hashCode()
      result = result * 37 + focusable.hashCode()
      result = result * 37 + editable.hashCode()
      result = result * 37 + resource_id.hashCode()
      result = result * 37 + depth.hashCode()
      result = result * 37 + children.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """avid=${sanitize(avid)}"""
    result += """package_name=${sanitize(package_name)}"""
    result += """class_name=${sanitize(class_name)}"""
    result += """text=${sanitize(text)}"""
    result += """content_desc=${sanitize(content_desc)}"""
    if (bounds != null) result += """bounds=$bounds"""
    result += """clickable=$clickable"""
    result += """scrollable=$scrollable"""
    result += """focusable=$focusable"""
    result += """editable=$editable"""
    result += """resource_id=${sanitize(resource_id)}"""
    result += """depth=$depth"""
    if (children.isNotEmpty()) result += """children=$children"""
    return result.joinToString(prefix = "AvidElement{", separator = ", ", postfix = "}")
  }

  public fun copy(
    avid: String = this.avid,
    package_name: String = this.package_name,
    class_name: String = this.class_name,
    text: String = this.text,
    content_desc: String = this.content_desc,
    bounds: Bounds? = this.bounds,
    clickable: Boolean = this.clickable,
    scrollable: Boolean = this.scrollable,
    focusable: Boolean = this.focusable,
    editable: Boolean = this.editable,
    resource_id: String = this.resource_id,
    depth: Int = this.depth,
    children: List<AvidElement> = this.children,
    unknownFields: ByteString = this.unknownFields,
  ): AvidElement = AvidElement(avid, package_name, class_name, text, content_desc, bounds,
      clickable, scrollable, focusable, editable, resource_id, depth, children, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AvidElement> = object : ProtoAdapter<AvidElement>(
      FieldEncoding.LENGTH_DELIMITED,
      AvidElement::class,
      "type.googleapis.com/com.augmentalis.universalrpc.avid.AvidElement",
      PROTO_3,
      null,
      "avid.proto"
    ) {
      override fun encodedSize(`value`: AvidElement): Int {
        var size = value.unknownFields.size
        if (value.avid != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.avid)
        }
        if (value.package_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.package_name)
        }
        if (value.class_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.class_name)
        }
        if (value.text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.text)
        }
        if (value.content_desc != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.content_desc)
        }
        if (value.bounds != null) {
          size += Bounds.ADAPTER.encodedSizeWithTag(6, value.bounds)
        }
        if (value.clickable != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(7, value.clickable)
        }
        if (value.scrollable != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(8, value.scrollable)
        }
        if (value.focusable != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(9, value.focusable)
        }
        if (value.editable != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(10, value.editable)
        }
        if (value.resource_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(11, value.resource_id)
        }
        if (value.depth != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(12, value.depth)
        }
        size += AvidElement.ADAPTER.asRepeated().encodedSizeWithTag(13, value.children)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AvidElement) {
        if (value.avid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.avid)
        }
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        if (value.class_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.class_name)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.text)
        }
        if (value.content_desc != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.content_desc)
        }
        if (value.bounds != null) {
          Bounds.ADAPTER.encodeWithTag(writer, 6, value.bounds)
        }
        if (value.clickable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.clickable)
        }
        if (value.scrollable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.scrollable)
        }
        if (value.focusable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 9, value.focusable)
        }
        if (value.editable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 10, value.editable)
        }
        if (value.resource_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.resource_id)
        }
        if (value.depth != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 12, value.depth)
        }
        AvidElement.ADAPTER.asRepeated().encodeWithTag(writer, 13, value.children)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AvidElement) {
        writer.writeBytes(value.unknownFields)
        AvidElement.ADAPTER.asRepeated().encodeWithTag(writer, 13, value.children)
        if (value.depth != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 12, value.depth)
        }
        if (value.resource_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.resource_id)
        }
        if (value.editable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 10, value.editable)
        }
        if (value.focusable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 9, value.focusable)
        }
        if (value.scrollable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.scrollable)
        }
        if (value.clickable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.clickable)
        }
        if (value.bounds != null) {
          Bounds.ADAPTER.encodeWithTag(writer, 6, value.bounds)
        }
        if (value.content_desc != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.content_desc)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.text)
        }
        if (value.class_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.class_name)
        }
        if (value.package_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.package_name)
        }
        if (value.avid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.avid)
        }
      }

      override fun decode(reader: ProtoReader): AvidElement {
        var avid: String = ""
        var package_name: String = ""
        var class_name: String = ""
        var text: String = ""
        var content_desc: String = ""
        var bounds: Bounds? = null
        var clickable: Boolean = false
        var scrollable: Boolean = false
        var focusable: Boolean = false
        var editable: Boolean = false
        var resource_id: String = ""
        var depth: Int = 0
        val children = mutableListOf<AvidElement>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> avid = ProtoAdapter.STRING.decode(reader)
            2 -> package_name = ProtoAdapter.STRING.decode(reader)
            3 -> class_name = ProtoAdapter.STRING.decode(reader)
            4 -> text = ProtoAdapter.STRING.decode(reader)
            5 -> content_desc = ProtoAdapter.STRING.decode(reader)
            6 -> bounds = Bounds.ADAPTER.decode(reader)
            7 -> clickable = ProtoAdapter.BOOL.decode(reader)
            8 -> scrollable = ProtoAdapter.BOOL.decode(reader)
            9 -> focusable = ProtoAdapter.BOOL.decode(reader)
            10 -> editable = ProtoAdapter.BOOL.decode(reader)
            11 -> resource_id = ProtoAdapter.STRING.decode(reader)
            12 -> depth = ProtoAdapter.INT32.decode(reader)
            13 -> children.add(AvidElement.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return AvidElement(
          avid = avid,
          package_name = package_name,
          class_name = class_name,
          text = text,
          content_desc = content_desc,
          bounds = bounds,
          clickable = clickable,
          scrollable = scrollable,
          focusable = focusable,
          editable = editable,
          resource_id = resource_id,
          depth = depth,
          children = children,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AvidElement): AvidElement = value.copy(
        bounds = value.bounds?.let(Bounds.ADAPTER::redact),
        children = value.children.redactElements(AvidElement.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
