// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.avid.AvidCreatorService in avid.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.avid

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import com.squareup.wire.GrpcStreamingCall
import kotlin.Suppress

/**
 * Service definition
 */
public class GrpcAvidCreatorServiceClient(
  private val client: GrpcClient,
) : AvidCreatorServiceClient {
  /**
   * Query element by various criteria
   */
  override fun QueryElement(): GrpcCall<ElementQueryRequest, AvidCommandResult> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.avid.AvidCreatorService/QueryElement",
      requestAdapter = ElementQueryRequest.ADAPTER,
      responseAdapter = AvidCommandResult.ADAPTER
  ))

  /**
   * Scrape current screen
   */
  override fun ScrapeScreen(): GrpcCall<ScrapeRequest, ScrapeResponse> = client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.avid.AvidCreatorService/ScrapeScreen",
      requestAdapter = ScrapeRequest.ADAPTER,
      responseAdapter = ScrapeResponse.ADAPTER
  ))

  /**
   * Execute action on element
   */
  override fun ExecuteAction(): GrpcCall<ElementActionRequest, AvidCommandResult> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.avid.AvidCreatorService/ExecuteAction",
      requestAdapter = ElementActionRequest.ADAPTER,
      responseAdapter = AvidCommandResult.ADAPTER
  ))

  /**
   * Generate AVID for element
   */
  override fun GenerateAvid(): GrpcCall<GenerateAvidRequest, AvidCommandResult> =
      client.newCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.avid.AvidCreatorService/GenerateAvid",
      requestAdapter = GenerateAvidRequest.ADAPTER,
      responseAdapter = AvidCommandResult.ADAPTER
  ))

  /**
   * Stream screen changes
   */
  override fun StreamScreenChanges(): GrpcStreamingCall<StreamScreenRequest, ScrapeResponse> =
      client.newStreamingCall(GrpcMethod(
      path = "/com.augmentalis.universalrpc.avid.AvidCreatorService/StreamScreenChanges",
      requestAdapter = StreamScreenRequest.ADAPTER,
      responseAdapter = ScrapeResponse.ADAPTER
  ))
}
