// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.cockpit.DevicesResponse in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class DevicesResponse(
  devices: List<DeviceInfo> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DevicesResponse, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.augmentalis.universalrpc.cockpit.DeviceInfo#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val devices: List<DeviceInfo> = immutableCopyOf("devices", devices)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DevicesResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (devices != other.devices) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + devices.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (devices.isNotEmpty()) result += """devices=$devices"""
    return result.joinToString(prefix = "DevicesResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(devices: List<DeviceInfo> = this.devices, unknownFields: ByteString =
      this.unknownFields): DevicesResponse = DevicesResponse(devices, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DevicesResponse> = object : ProtoAdapter<DevicesResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      DevicesResponse::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.cockpit.DevicesResponse", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: DevicesResponse): Int {
        var size = value.unknownFields.size
        size += DeviceInfo.ADAPTER.asRepeated().encodedSizeWithTag(1, value.devices)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DevicesResponse) {
        DeviceInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.devices)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DevicesResponse) {
        writer.writeBytes(value.unknownFields)
        DeviceInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.devices)
      }

      override fun decode(reader: ProtoReader): DevicesResponse {
        val devices = mutableListOf<DeviceInfo>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> devices.add(DeviceInfo.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return DevicesResponse(
          devices = devices,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DevicesResponse): DevicesResponse = value.copy(
        devices = value.devices.redactElements(DeviceInfo.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
