// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.cockpit.DeviceInfo in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * Device info
 */
public class DeviceInfo(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "deviceId",
    schemaIndex = 0,
  )
  public val device_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val name: String = "",
  /**
   * "android", "ios", "desktop", "web"
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val platform: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val version: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val online: Boolean = false,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lastSeen",
    schemaIndex = 5,
  )
  public val last_seen: Long = 0L,
  capabilities: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DeviceInfo, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 7,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 6,
  )
  public val capabilities: Map<String, String> = immutableCopyOf("capabilities", capabilities)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DeviceInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (device_id != other.device_id) return false
    if (name != other.name) return false
    if (platform != other.platform) return false
    if (version != other.version) return false
    if (online != other.online) return false
    if (last_seen != other.last_seen) return false
    if (capabilities != other.capabilities) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + device_id.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + platform.hashCode()
      result = result * 37 + version.hashCode()
      result = result * 37 + online.hashCode()
      result = result * 37 + last_seen.hashCode()
      result = result * 37 + capabilities.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """device_id=${sanitize(device_id)}"""
    result += """name=${sanitize(name)}"""
    result += """platform=${sanitize(platform)}"""
    result += """version=${sanitize(version)}"""
    result += """online=$online"""
    result += """last_seen=$last_seen"""
    if (capabilities.isNotEmpty()) result += """capabilities=$capabilities"""
    return result.joinToString(prefix = "DeviceInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    device_id: String = this.device_id,
    name: String = this.name,
    platform: String = this.platform,
    version: String = this.version,
    online: Boolean = this.online,
    last_seen: Long = this.last_seen,
    capabilities: Map<String, String> = this.capabilities,
    unknownFields: ByteString = this.unknownFields,
  ): DeviceInfo = DeviceInfo(device_id, name, platform, version, online, last_seen, capabilities,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DeviceInfo> = object : ProtoAdapter<DeviceInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      DeviceInfo::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.cockpit.DeviceInfo", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      private val capabilitiesAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: DeviceInfo): Int {
        var size = value.unknownFields.size
        if (value.device_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.device_id)
        }
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.name)
        }
        if (value.platform != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.platform)
        }
        if (value.version != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.version)
        }
        if (value.online != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(5, value.online)
        }
        if (value.last_seen != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(6, value.last_seen)
        }
        size += capabilitiesAdapter.encodedSizeWithTag(7, value.capabilities)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DeviceInfo) {
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.device_id)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        }
        if (value.platform != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.platform)
        }
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.version)
        }
        if (value.online != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.online)
        }
        if (value.last_seen != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 6, value.last_seen)
        }
        capabilitiesAdapter.encodeWithTag(writer, 7, value.capabilities)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DeviceInfo) {
        writer.writeBytes(value.unknownFields)
        capabilitiesAdapter.encodeWithTag(writer, 7, value.capabilities)
        if (value.last_seen != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 6, value.last_seen)
        }
        if (value.online != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.online)
        }
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.version)
        }
        if (value.platform != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.platform)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        }
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.device_id)
        }
      }

      override fun decode(reader: ProtoReader): DeviceInfo {
        var device_id: String = ""
        var name: String = ""
        var platform: String = ""
        var version: String = ""
        var online: Boolean = false
        var last_seen: Long = 0L
        val capabilities = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> device_id = ProtoAdapter.STRING.decode(reader)
            2 -> name = ProtoAdapter.STRING.decode(reader)
            3 -> platform = ProtoAdapter.STRING.decode(reader)
            4 -> version = ProtoAdapter.STRING.decode(reader)
            5 -> online = ProtoAdapter.BOOL.decode(reader)
            6 -> last_seen = ProtoAdapter.INT64.decode(reader)
            7 -> capabilities.putAll(capabilitiesAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return DeviceInfo(
          device_id = device_id,
          name = name,
          platform = platform,
          version = version,
          online = online,
          last_seen = last_seen,
          capabilities = capabilities,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DeviceInfo): DeviceInfo = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
