// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.cockpit.LayoutsResponse in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class LayoutsResponse(
  presets: List<LayoutPreset> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LayoutsResponse, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.augmentalis.universalrpc.cockpit.LayoutPreset#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val presets: List<LayoutPreset> = immutableCopyOf("presets", presets)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LayoutsResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (presets != other.presets) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + presets.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (presets.isNotEmpty()) result += """presets=$presets"""
    return result.joinToString(prefix = "LayoutsResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(presets: List<LayoutPreset> = this.presets, unknownFields: ByteString =
      this.unknownFields): LayoutsResponse = LayoutsResponse(presets, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LayoutsResponse> = object : ProtoAdapter<LayoutsResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      LayoutsResponse::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.cockpit.LayoutsResponse", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: LayoutsResponse): Int {
        var size = value.unknownFields.size
        size += LayoutPreset.ADAPTER.asRepeated().encodedSizeWithTag(1, value.presets)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LayoutsResponse) {
        LayoutPreset.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.presets)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LayoutsResponse) {
        writer.writeBytes(value.unknownFields)
        LayoutPreset.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.presets)
      }

      override fun decode(reader: ProtoReader): LayoutsResponse {
        val presets = mutableListOf<LayoutPreset>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> presets.add(LayoutPreset.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return LayoutsResponse(
          presets = presets,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LayoutsResponse): LayoutsResponse = value.copy(
        presets = value.presets.redactElements(LayoutPreset.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
