// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.cockpit.LayoutPreset in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Layout preset
 */
public class LayoutPreset(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "presetId",
    schemaIndex = 0,
  )
  public val preset_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val name: String = "",
  windows: List<WindowLayout> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LayoutPreset, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 3,
    adapter = "com.augmentalis.universalrpc.cockpit.WindowLayout#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val windows: List<WindowLayout> = immutableCopyOf("windows", windows)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LayoutPreset) return false
    if (unknownFields != other.unknownFields) return false
    if (preset_id != other.preset_id) return false
    if (name != other.name) return false
    if (windows != other.windows) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + preset_id.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + windows.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """preset_id=${sanitize(preset_id)}"""
    result += """name=${sanitize(name)}"""
    if (windows.isNotEmpty()) result += """windows=$windows"""
    return result.joinToString(prefix = "LayoutPreset{", separator = ", ", postfix = "}")
  }

  public fun copy(
    preset_id: String = this.preset_id,
    name: String = this.name,
    windows: List<WindowLayout> = this.windows,
    unknownFields: ByteString = this.unknownFields,
  ): LayoutPreset = LayoutPreset(preset_id, name, windows, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LayoutPreset> = object : ProtoAdapter<LayoutPreset>(
      FieldEncoding.LENGTH_DELIMITED, 
      LayoutPreset::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.cockpit.LayoutPreset", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: LayoutPreset): Int {
        var size = value.unknownFields.size
        if (value.preset_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.preset_id)
        }
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.name)
        }
        size += WindowLayout.ADAPTER.asRepeated().encodedSizeWithTag(3, value.windows)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LayoutPreset) {
        if (value.preset_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.preset_id)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        }
        WindowLayout.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.windows)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LayoutPreset) {
        writer.writeBytes(value.unknownFields)
        WindowLayout.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.windows)
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        }
        if (value.preset_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.preset_id)
        }
      }

      override fun decode(reader: ProtoReader): LayoutPreset {
        var preset_id: String = ""
        var name: String = ""
        val windows = mutableListOf<WindowLayout>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> preset_id = ProtoAdapter.STRING.decode(reader)
            2 -> name = ProtoAdapter.STRING.decode(reader)
            3 -> windows.add(WindowLayout.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return LayoutPreset(
          preset_id = preset_id,
          name = name,
          windows = windows,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LayoutPreset): LayoutPreset = value.copy(
        windows = value.windows.redactElements(WindowLayout.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
