// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.cockpit.SyncRequest in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Sync request
 */
public class SyncRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sourceDevice",
    schemaIndex = 1,
  )
  public val source_device: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "targetDevice",
    schemaIndex = 2,
  )
  public val target_device: String = "",
  data_types: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SyncRequest, Nothing>(ADAPTER, unknownFields) {
  /**
   * "settings", "commands", "learned_apps"
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "dataTypes",
    schemaIndex = 3,
  )
  public val data_types: List<String> = immutableCopyOf("data_types", data_types)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SyncRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (source_device != other.source_device) return false
    if (target_device != other.target_device) return false
    if (data_types != other.data_types) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + source_device.hashCode()
      result = result * 37 + target_device.hashCode()
      result = result * 37 + data_types.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """source_device=${sanitize(source_device)}"""
    result += """target_device=${sanitize(target_device)}"""
    if (data_types.isNotEmpty()) result += """data_types=${sanitize(data_types)}"""
    return result.joinToString(prefix = "SyncRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    source_device: String = this.source_device,
    target_device: String = this.target_device,
    data_types: List<String> = this.data_types,
    unknownFields: ByteString = this.unknownFields,
  ): SyncRequest = SyncRequest(request_id, source_device, target_device, data_types, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SyncRequest> = object : ProtoAdapter<SyncRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      SyncRequest::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.cockpit.SyncRequest", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: SyncRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.source_device != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.source_device)
        }
        if (value.target_device != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.target_device)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(4, value.data_types)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SyncRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.source_device != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.source_device)
        }
        if (value.target_device != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.target_device)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.data_types)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SyncRequest) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.data_types)
        if (value.target_device != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.target_device)
        }
        if (value.source_device != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.source_device)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): SyncRequest {
        var request_id: String = ""
        var source_device: String = ""
        var target_device: String = ""
        val data_types = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> source_device = ProtoAdapter.STRING.decode(reader)
            3 -> target_device = ProtoAdapter.STRING.decode(reader)
            4 -> data_types.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return SyncRequest(
          request_id = request_id,
          source_device = source_device,
          target_device = target_device,
          data_types = data_types,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SyncRequest): SyncRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
