// Author: Manoj Jhawar
// Code-Reviewed-By: CCA

package com.augmentalis.database.dto

import kotlinx.datetime.Clock

/**
 * Data Transfer Object for CommandUsage table.
 * Tracks command usage for analytics and learning.
 *
 * Corresponds to CommandUsage.sq schema.
 * Extended with locale, userInput, matchType, executionTimeMs, contextApp for CommandManager compatibility.
 */
data class CommandUsageDTO(
    val id: Long,
    val commandId: String,
    val locale: String = "en-US",
    val timestamp: Long,
    val userInput: String = "",
    val matchType: String = "EXACT",
    val success: Long,
    val executionTimeMs: Long = 0,
    val contextApp: String? = null,
    val contextKey: String = ""
) {
    companion object {
        /**
         * Create a new CommandUsageDTO for successful command.
         */
        fun success(
            commandId: String,
            contextKey: String,
            locale: String = "en-US",
            userInput: String = "",
            matchType: String = "EXACT",
            executionTimeMs: Long = 0,
            contextApp: String? = null
        ): CommandUsageDTO {
            return CommandUsageDTO(
                id = 0, // Will be auto-generated by database
                commandId = commandId,
                locale = locale,
                timestamp = Clock.System.now().toEpochMilliseconds(),
                userInput = userInput,
                matchType = matchType,
                success = 1L,
                executionTimeMs = executionTimeMs,
                contextApp = contextApp,
                contextKey = contextKey
            )
        }

        /**
         * Create a new CommandUsageDTO for failed command.
         */
        fun failure(
            commandId: String,
            contextKey: String,
            locale: String = "en-US",
            userInput: String = "",
            executionTimeMs: Long = 0,
            contextApp: String? = null
        ): CommandUsageDTO {
            return CommandUsageDTO(
                id = 0, // Will be auto-generated by database
                commandId = commandId,
                locale = locale,
                timestamp = Clock.System.now().toEpochMilliseconds(),
                userInput = userInput,
                matchType = "NONE",
                success = 0L,
                executionTimeMs = executionTimeMs,
                contextApp = contextApp,
                contextKey = contextKey
            )
        }
    }
}

/**
 * Extension to convert SQLDelight entity to DTO.
 */
fun com.augmentalis.database.Command_usage.toDTO(): CommandUsageDTO = CommandUsageDTO(
    id = id,
    commandId = command_id,
    locale = locale,
    timestamp = timestamp,
    userInput = user_input,
    matchType = match_type,
    success = success,
    executionTimeMs = execution_time_ms,
    contextApp = context_app,
    contextKey = context_key
)
