// Author: Manoj Jhawar
// Code-Reviewed-By: CCA

package com.augmentalis.database.dto

import kotlinx.datetime.Clock

/**
 * Data Transfer Object for ContextPreference table.
 * Tracks command preferences per context for adaptive learning.
 *
 * Corresponds to ContextPreference.sq schema.
 */
data class ContextPreferenceDTO(
    val id: Long,
    val commandId: String,
    val contextKey: String,
    val usageCount: Long,
    val successCount: Long,
    val lastUsedTimestamp: Long
) {
    /**
     * Calculate success rate.
     */
    val successRate: Double
        get() = if (usageCount > 0) successCount.toDouble() / usageCount.toDouble() else 0.0

    companion object {
        /**
         * Create a new ContextPreferenceDTO.
         */
        fun create(
            commandId: String,
            contextKey: String,
            usageCount: Long = 0,
            successCount: Long = 0
        ): ContextPreferenceDTO {
            return ContextPreferenceDTO(
                id = 0, // Will be auto-generated by database
                commandId = commandId,
                contextKey = contextKey,
                usageCount = usageCount,
                successCount = successCount,
                lastUsedTimestamp = Clock.System.now().toEpochMilliseconds()
            )
        }
    }
}

/**
 * Extension to convert SQLDelight entity to DTO.
 */
fun com.augmentalis.database.Context_preference.toContextPreferenceDTO(): ContextPreferenceDTO = ContextPreferenceDTO(
    id = id,
    commandId = command_id,
    contextKey = context_key,
    usageCount = usage_count,
    successCount = success_count,
    lastUsedTimestamp = last_used_timestamp
)
