#!/bin/bash
# Generate comprehensive file-by-file, class-by-class API documentation for VOS4 codebase
# Created: 2025-10-19 21:11 PDT

set -e

PROJECT_ROOT="/Volumes/M Drive/Coding/vos4"
OUTPUT_DIR="$PROJECT_ROOT/docs/reference/api-complete"
TIMESTAMP=$(date "+%y%m%d-%H%M")

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  VOS4 Complete API Documentation Generator${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Function to extract package from file
extract_package() {
    local file="$1"
    grep "^package " "$file" | head -1 | sed 's/package //;s/;$//' || echo "unknown"
}

# Function to extract classes/interfaces/objects
extract_classes() {
    local file="$1"
    # Match: class, interface, object, data class, sealed class, enum class
    grep -E "^(class|interface|object|data class|sealed class|enum class|abstract class) " "$file" | \
        sed 's/[:{].*//' | \
        sed 's/^/  - /' || echo "  - (no public classes)"
}

# Function to extract public functions
extract_functions() {
    local file="$1"
    grep -E "^(fun|suspend fun|inline fun|public fun) " "$file" | \
        sed 's/{.*//' | \
        sed 's/^/  - /' || echo "  - (no public functions)"
}

# Function to process module
process_module() {
    local module_type="$1"  # apps, libraries, managers
    local module_name="$2"
    local module_path="$PROJECT_ROOT/modules/$module_type/$module_name"

    if [ ! -d "$module_path" ]; then
        echo -e "${YELLOW}Warning: Module not found: $module_path${NC}"
        return
    fi

    echo -e "${GREEN}Processing: $module_type/$module_name${NC}"

    local output_file="$OUTPUT_DIR/${module_name}-API-Reference-${TIMESTAMP}.md"

    # Write header
    cat > "$output_file" <<EOF
# $module_name - Complete API Reference

**Module Type:** $module_type
**Generated:** $(date "+%Y-%m-%d %H:%M:%S %Z")
**Timestamp:** $TIMESTAMP
**Location:** \`modules/$module_type/$module_name\`

---

## Overview

This document provides a complete file-by-file, class-by-class reference for the $module_name module.

## Files

EOF

    # Find all Kotlin/Java files
    local file_count=0
    while IFS= read -r file; do
        ((file_count++))

        local rel_path="${file#$module_path/}"
        local package=$(extract_package "$file")

        echo "" >> "$output_file"
        echo "### File: \`$rel_path\`" >> "$output_file"
        echo "" >> "$output_file"
        echo "**Package:** \`$package\`" >> "$output_file"
        echo "" >> "$output_file"

        # Extract classes
        echo "**Classes/Interfaces/Objects:**" >> "$output_file"
        extract_classes "$file" >> "$output_file"
        echo "" >> "$output_file"

        # Extract functions
        echo "**Public Functions:**" >> "$output_file"
        extract_functions "$file" >> "$output_file"
        echo "" >> "$output_file"

        echo "**Imports:**" >> "$output_file"
        grep "^import " "$file" | sed 's/^/  - /' | head -10 >> "$output_file"
        local import_count=$(grep "^import " "$file" | wc -l)
        if [ "$import_count" -gt 10 ]; then
            echo "  - ... and $((import_count - 10)) more" >> "$output_file"
        fi
        echo "" >> "$output_file"
        echo "---" >> "$output_file"

    done < <(find "$module_path" -type f \( -name "*.kt" -o -name "*.java" \) | sort)

    # Write summary
    cat >> "$output_file" <<EOF

## Summary

**Total Files:** $file_count

**Module Structure:**
\`\`\`
$(tree -L 3 -d "$module_path" 2>/dev/null || ls -R "$module_path" | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//  /g' -e 's/^/  /' | head -50)
\`\`\`

---

**Generated by:** VOS4 API Documentation Generator
**Timestamp:** $TIMESTAMP
EOF

    echo -e "  ${GREEN}✓${NC} Created: $output_file ($file_count files)"
}

# Process all apps
echo -e "${BLUE}Processing Apps...${NC}"
process_module "apps" "LearnApp"
process_module "apps" "VoiceCursor"
process_module "apps" "VoiceOSCore"
process_module "apps" "VoiceRecognition"
process_module "apps" "VoiceUI"

# Process all libraries
echo -e "${BLUE}Processing Libraries...${NC}"
process_module "libraries" "DeviceManager"
process_module "libraries" "MagicElements"
process_module "libraries" "MagicUI"
process_module "libraries" "SpeechRecognition"
process_module "libraries" "Translation"
process_module "libraries" "UUIDCreator"
process_module "libraries" "VoiceKeyboard"
process_module "libraries" "VoiceOsLogger"
process_module "libraries" "VoiceUIElements"

# Process all managers
echo -e "${BLUE}Processing Managers...${NC}"
process_module "managers" "CommandManager"
process_module "managers" "HUDManager"
process_module "managers" "LicenseManager"
process_module "managers" "LocalizationManager"
process_module "managers" "VoiceDataManager"

# Create master index
echo -e "${BLUE}Creating master index...${NC}"

cat > "$OUTPUT_DIR/00-API-Reference-Index-${TIMESTAMP}.md" <<EOF
# VOS4 Complete API Reference - Master Index

**Generated:** $(date "+%Y-%m-%d %H:%M:%S %Z")
**Timestamp:** $TIMESTAMP
**Total Modules:** 19

---

## Purpose

This is the master index for VOS4's complete file-by-file, class-by-class API documentation.

## Structure

Each module has its own comprehensive API reference document listing:
- All source files
- All classes, interfaces, objects, data classes
- All public functions and their signatures
- All public properties
- Package structure
- Dependencies (imports)

---

## Apps (5 modules)

1. **LearnApp** - [LearnApp-API-Reference-${TIMESTAMP}.md](LearnApp-API-Reference-${TIMESTAMP}.md)
2. **VoiceCursor** - [VoiceCursor-API-Reference-${TIMESTAMP}.md](VoiceCursor-API-Reference-${TIMESTAMP}.md)
3. **VoiceOSCore** - [VoiceOSCore-API-Reference-${TIMESTAMP}.md](VoiceOSCore-API-Reference-${TIMESTAMP}.md)
4. **VoiceRecognition** - [VoiceRecognition-API-Reference-${TIMESTAMP}.md](VoiceRecognition-API-Reference-${TIMESTAMP}.md)
5. **VoiceUI** - [VoiceUI-API-Reference-${TIMESTAMP}.md](VoiceUI-API-Reference-${TIMESTAMP}.md)

## Libraries (9 modules)

6. **DeviceManager** - [DeviceManager-API-Reference-${TIMESTAMP}.md](DeviceManager-API-Reference-${TIMESTAMP}.md)
7. **MagicElements** - [MagicElements-API-Reference-${TIMESTAMP}.md](MagicElements-API-Reference-${TIMESTAMP}.md)
8. **MagicUI** - [MagicUI-API-Reference-${TIMESTAMP}.md](MagicUI-API-Reference-${TIMESTAMP}.md)
9. **SpeechRecognition** - [SpeechRecognition-API-Reference-${TIMESTAMP}.md](SpeechRecognition-API-Reference-${TIMESTAMP}.md)
10. **Translation** - [Translation-API-Reference-${TIMESTAMP}.md](Translation-API-Reference-${TIMESTAMP}.md)
11. **UUIDCreator** - [UUIDCreator-API-Reference-${TIMESTAMP}.md](UUIDCreator-API-Reference-${TIMESTAMP}.md)
12. **VoiceKeyboard** - [VoiceKeyboard-API-Reference-${TIMESTAMP}.md](VoiceKeyboard-API-Reference-${TIMESTAMP}.md)
13. **VoiceOsLogger** - [VoiceOsLogger-API-Reference-${TIMESTAMP}.md](VoiceOsLogger-API-Reference-${TIMESTAMP}.md)
14. **VoiceUIElements** - [VoiceUIElements-API-Reference-${TIMESTAMP}.md](VoiceUIElements-API-Reference-${TIMESTAMP}.md)

## Managers (5 modules)

15. **CommandManager** - [CommandManager-API-Reference-${TIMESTAMP}.md](CommandManager-API-Reference-${TIMESTAMP}.md)
16. **HUDManager** - [HUDManager-API-Reference-${TIMESTAMP}.md](HUDManager-API-Reference-${TIMESTAMP}.md)
17. **LicenseManager** - [LicenseManager-API-Reference-${TIMESTAMP}.md](LicenseManager-API-Reference-${TIMESTAMP}.md)
18. **LocalizationManager** - [LocalizationManager-API-Reference-${TIMESTAMP}.md](LocalizationManager-API-Reference-${TIMESTAMP}.md)
19. **VoiceDataManager** - [VoiceDataManager-API-Reference-${TIMESTAMP}.md](VoiceDataManager-API-Reference-${TIMESTAMP}.md)

---

## Usage

**Finding a specific class:**
1. Determine which module it belongs to
2. Open that module's API reference
3. Search for the class name

**Understanding module structure:**
Each API reference includes:
- Complete file listing
- Package organization
- Class hierarchy
- Function signatures
- Import dependencies

**For developers:**
This documentation is auto-generated from the codebase and should be regenerated after major refactoring.

**Regenerate:**
\`\`\`bash
cd /Volumes/M Drive/Coding/vos4
./docs/scripts/generate-codebase-api-docs.sh
\`\`\`

---

## Statistics

**Total Source Files:** $(find "$PROJECT_ROOT/modules" -name "*.kt" -o -name "*.java" | wc -l | xargs)
**Apps:** 5 modules
**Libraries:** 9 modules
**Managers:** 5 modules
**Total Modules:** 19

---

**Generated by:** VOS4 API Documentation Generator
**Location:** \`docs/reference/api-complete/\`
**Timestamp:** $TIMESTAMP
EOF

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✅ API Documentation Generation Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}Output Directory:${NC}"
echo "  $OUTPUT_DIR"
echo ""
echo -e "${YELLOW}Master Index:${NC}"
echo "  $OUTPUT_DIR/00-API-Reference-Index-${TIMESTAMP}.md"
echo ""
echo -e "${YELLOW}Total Modules:${NC} 19"
echo -e "${YELLOW}Total Source Files:${NC} $(find "$PROJECT_ROOT/modules" -name "*.kt" -o -name "*.java" | wc -l | xargs)"
echo ""
