// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.cockpit.GetWindowsRequest in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class GetWindowsRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 0,
  )
  public val request_id: String = "",
  /**
   * Optional filter
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "deviceId",
    schemaIndex = 1,
  )
  public val device_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetWindowsRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetWindowsRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (request_id != other.request_id) return false
    if (device_id != other.device_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + device_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """request_id=${sanitize(request_id)}"""
    result += """device_id=${sanitize(device_id)}"""
    return result.joinToString(prefix = "GetWindowsRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    request_id: String = this.request_id,
    device_id: String = this.device_id,
    unknownFields: ByteString = this.unknownFields,
  ): GetWindowsRequest = GetWindowsRequest(request_id, device_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetWindowsRequest> = object : ProtoAdapter<GetWindowsRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetWindowsRequest::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.cockpit.GetWindowsRequest", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: GetWindowsRequest): Int {
        var size = value.unknownFields.size
        if (value.request_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.request_id)
        }
        if (value.device_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.device_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetWindowsRequest) {
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.device_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetWindowsRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.device_id)
        }
        if (value.request_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.request_id)
        }
      }

      override fun decode(reader: ProtoReader): GetWindowsRequest {
        var request_id: String = ""
        var device_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> request_id = ProtoAdapter.STRING.decode(reader)
            2 -> device_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetWindowsRequest(
          request_id = request_id,
          device_id = device_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetWindowsRequest): GetWindowsRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
