// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.augmentalis.universalrpc.cockpit.WindowLayout in cockpit.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.augmentalis.universalrpc.cockpit

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class WindowLayout(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "windowId",
    schemaIndex = 0,
  )
  public val window_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val x: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val y: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val width: Int = 0,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val height: Int = 0,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "displayId",
    schemaIndex = 5,
  )
  public val display_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<WindowLayout, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is WindowLayout) return false
    if (unknownFields != other.unknownFields) return false
    if (window_id != other.window_id) return false
    if (x != other.x) return false
    if (y != other.y) return false
    if (width != other.width) return false
    if (height != other.height) return false
    if (display_id != other.display_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + window_id.hashCode()
      result = result * 37 + x.hashCode()
      result = result * 37 + y.hashCode()
      result = result * 37 + width.hashCode()
      result = result * 37 + height.hashCode()
      result = result * 37 + display_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """window_id=${sanitize(window_id)}"""
    result += """x=$x"""
    result += """y=$y"""
    result += """width=$width"""
    result += """height=$height"""
    result += """display_id=${sanitize(display_id)}"""
    return result.joinToString(prefix = "WindowLayout{", separator = ", ", postfix = "}")
  }

  public fun copy(
    window_id: String = this.window_id,
    x: Int = this.x,
    y: Int = this.y,
    width: Int = this.width,
    height: Int = this.height,
    display_id: String = this.display_id,
    unknownFields: ByteString = this.unknownFields,
  ): WindowLayout = WindowLayout(window_id, x, y, width, height, display_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<WindowLayout> = object : ProtoAdapter<WindowLayout>(
      FieldEncoding.LENGTH_DELIMITED, 
      WindowLayout::class, 
      "type.googleapis.com/com.augmentalis.universalrpc.cockpit.WindowLayout", 
      PROTO_3, 
      null, 
      "cockpit.proto"
    ) {
      override fun encodedSize(`value`: WindowLayout): Int {
        var size = value.unknownFields.size
        if (value.window_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.window_id)
        }
        if (value.x != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.x)
        }
        if (value.y != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.y)
        }
        if (value.width != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.width)
        }
        if (value.height != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.height)
        }
        if (value.display_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.display_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: WindowLayout) {
        if (value.window_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.window_id)
        }
        if (value.x != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.x)
        }
        if (value.y != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.y)
        }
        if (value.width != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.width)
        }
        if (value.height != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.height)
        }
        if (value.display_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.display_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: WindowLayout) {
        writer.writeBytes(value.unknownFields)
        if (value.display_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.display_id)
        }
        if (value.height != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.height)
        }
        if (value.width != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.width)
        }
        if (value.y != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.y)
        }
        if (value.x != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.x)
        }
        if (value.window_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.window_id)
        }
      }

      override fun decode(reader: ProtoReader): WindowLayout {
        var window_id: String = ""
        var x: Int = 0
        var y: Int = 0
        var width: Int = 0
        var height: Int = 0
        var display_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> window_id = ProtoAdapter.STRING.decode(reader)
            2 -> x = ProtoAdapter.INT32.decode(reader)
            3 -> y = ProtoAdapter.INT32.decode(reader)
            4 -> width = ProtoAdapter.INT32.decode(reader)
            5 -> height = ProtoAdapter.INT32.decode(reader)
            6 -> display_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return WindowLayout(
          window_id = window_id,
          x = x,
          y = y,
          width = width,
          height = height,
          display_id = display_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: WindowLayout): WindowLayout = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
